export interface AngeCard {
  id: string;
  number: number;
  name: string;
  theme: string;
  message: string;
  guidance: string;
  affirmation: string;
  keywords: string[];
  color: string;
  crystal: string;
  chakra: string;
  emoji: string;
}

export const ANGEL_CARDS: AngeCard[] = [
  { id: "ariel", number: 1, name: "Ariel", theme: "Nature & Manifestation", message: "Vos besoins matériels sont comblés par l'abondance divine.", guidance: "L'Ange Ariel vous invite à faire confiance à la nature et à l'univers pour pourvoir à tous vos besoins. Connectez-vous à la terre, aux animaux et aux éléments naturels. La prospérité coule vers vous comme une source.", affirmation: "Je suis soutenu(e) par l'abondance infinie de l'univers.", keywords: ["abondance", "nature", "manifestation", "animaux", "prospérité"], color: "#90EE90", crystal: "Citrine", chakra: "Plexus solaire", emoji: "🌿" },
  { id: "azrael", number: 2, name: "Azraël", theme: "Transitions & Deuil", message: "Vous êtes entouré(e) d'amour divin dans les moments de perte.", guidance: "Azraël, l'ange des transitions, vous accompagne dans les moments de deuil ou de changement profond. Il n'y a pas de vraie séparation dans l'amour. Ceux que vous aimez vous entourent de leur lumière.", affirmation: "Je traverse cette transition avec grâce et amour.", keywords: ["deuil", "transition", "guérison", "amour", "paix"], color: "#E8E8FF", crystal: "Obsidienne noire", chakra: "Couronne", emoji: "🕊️" },
  { id: "chamuel", number: 3, name: "Chamuel", theme: "Amour & Relations", message: "L'amour que vous cherchez est déjà en vous.", guidance: "Chamuel, l'ange de l'amour pur, vous guide vers des relations harmonieuses. Si vous cherchez l'amour, commencez par vous aimer vous-même. Les relations qui vous correspondent vibrent à la même fréquence que votre cœur ouvert.", affirmation: "Mon cœur est ouvert à l'amour véritable.", keywords: ["amour", "relations", "compassion", "paix intérieure", "harmonie"], color: "#FFB6C1", crystal: "Quartz rose", chakra: "Cœur", emoji: "💗" },
  { id: "gabriel", number: 4, name: "Gabriel", theme: "Communication & Créativité", message: "Vos messages créatifs ont de l'importance. Exprimez-vous.", guidance: "Gabriel, le messager divin, vous encourage à exprimer votre vérité créative. Écriture, art, communication — vos dons sont nécessaires dans ce monde. Ne retenez plus votre voix.", affirmation: "Je m'exprime avec clarté, courage et créativité.", keywords: ["communication", "créativité", "écriture", "art", "message"], color: "#FFFACD", crystal: "Citrine", chakra: "Gorge", emoji: "📯" },
  { id: "haniel", number: 5, name: "Haniel", theme: "Amour, Beauté & Vénus", message: "Faites confiance à votre intuition — elle vous guide toujours juste.", guidance: "Haniel, l'ange de Vénus et de la sefira Netzach, vous invite à honorer la beauté, l'amour et votre sens esthétique profond. Vos émotions sont de précieux messagers. Ouvrez votre cœur à la grâce et à la douceur.", affirmation: "Je m'ouvre à la beauté et à l'amour qui m'entourent.", keywords: ["amour", "beauté", "Vénus", "sensibilité", "grâce"], color: "#C0C0FF", crystal: "Pierre de lune", chakra: "Cœur", emoji: "🌹" },
  { id: "jeremiel", number: 6, name: "Jérémiel", theme: "Revue de Vie & Émotions", message: "Regardez votre passé avec douceur — tout vous a mené ici.", guidance: "Jérémiel vous aide à faire le bilan de votre chemin de vie avec bienveillance. Chaque expérience avait un sens. Il est temps de comprendre les leçons reçues et de vous libérer de tout jugement envers vous-même.", affirmation: "Je m'accorde la douceur d'un regard bienveillant sur mon passé.", keywords: ["bilan", "émotions", "pardon", "compréhension", "leçons"], color: "#9B59B6", crystal: "Améthyste", chakra: "Troisième œil", emoji: "🔮" },
  { id: "jophiel", number: 7, name: "Jophiel", theme: "Beauté & Pensées Positives", message: "Embellissez vos pensées et votre environnement.", guidance: "Jophiel, l'ange de la beauté, vous invite à cultiver des pensées positives et à créer de la beauté autour de vous. Désencombrez votre espace, entourez-vous de ce qui vous inspire. La beauté extérieure reflète la paix intérieure.", affirmation: "Je crée de la beauté et de la joie dans chaque instant.", keywords: ["beauté", "positivité", "créativité", "inspiration", "clarté"], color: "#FFD700", crystal: "Citrine jaune", chakra: "Couronne", emoji: "✨" },
  { id: "metatron", number: 8, name: "Métatron", theme: "Enfants & Géométrie Sacrée", message: "Votre vie a un but sacré. Vous êtes exactement où vous devez être.", guidance: "Métatron, l'un des anges les plus puissants, travaille avec la géométrie sacrée et les enfants sensibles. Il vous aide à comprendre votre mission de vie et à ancrer votre lumière sur Terre. Faites confiance à votre chemin unique.", affirmation: "Je confie ma vie à mon chemin sacré.", keywords: ["mission de vie", "géométrie sacrée", "enfants", "ancrage", "lumière"], color: "#FF6B6B", crystal: "Cristal de roche", chakra: "Couronne", emoji: "⭐" },
  { id: "michael", number: 9, name: "Michaël", theme: "Protection & Courage", message: "Vous êtes protégé(e). Avancez sans crainte.", guidance: "Michaël, le guerrier de lumière, vous offre sa protection absolue. Appelez-le quand vous ressentez de la peur ou du danger. Il tranche les liens énergétiques négatifs avec son épée de lumière bleue et vous entoure d'un bouclier protecteur.", affirmation: "Je suis protégé(e) par la lumière divine.", keywords: ["protection", "courage", "force", "libération", "sécurité"], color: "#4169E1", crystal: "Lapis-lazuli", chakra: "Gorge", emoji: "⚔️" },
  { id: "muriel", number: 10, name: "Muriel", theme: "Émotions & Paix", message: "Vos émotions sont sacrées. Écoutez-les avec douceur.", guidance: "Muriel vous aide à accéder à votre paix intérieure et à honorer vos émotions sans jugement. Si vous vous sentez submergé(e), demandez à Muriel de vous aider à trouver le calme dans la tempête émotionnelle.", affirmation: "Je navigue mes émotions avec douceur et sagesse.", keywords: ["émotions", "paix", "sensibilité", "guérison", "douceur"], color: "#98FB98", crystal: "Aventurine", chakra: "Cœur", emoji: "🌊" },
  { id: "raguel", number: 11, name: "Raguel", theme: "Relations & Justice", message: "L'harmonie est restaurée dans vos relations.", guidance: "Raguel supervise les relations et s'assure que la justice et l'harmonie règnent entre les êtres. Si vous avez un conflit ou un malentendu, Raguel peut aider à rétablir la paix et la compréhension mutuelle.", affirmation: "Mes relations sont empreintes d'harmonie et de respect mutuel.", keywords: ["relations", "harmonie", "justice", "réconciliation", "paix"], color: "#87CEEB", crystal: "Aigue-marine", chakra: "Cœur", emoji: "⚖️" },
  { id: "raphael", number: 12, name: "Raphaël", theme: "Guérison & Voyages", message: "La guérison est en cours sur tous les plans.", guidance: "Raphaël, le grand guérisseur, vous enveloppe de sa lumière verte émeraude. Qu'il s'agisse de guérison physique, émotionnelle ou spirituelle, sa présence accélère votre processus. Il protège également vos voyages.", affirmation: "Je suis en parfaite guérison sur tous les plans.", keywords: ["guérison", "santé", "voyage", "lumière verte", "bien-être"], color: "#50C878", crystal: "Malachite", chakra: "Cœur", emoji: "💚" },
  { id: "raziel", number: 13, name: "Raziel", theme: "Secrets Divins & Magie", message: "Les secrets de l'univers se révèlent à vous.", guidance: "Raziel est l'ange des mystères divins et de la magie. Il vous aide à comprendre les lois universelles et à développer vos dons spirituels. Un enseignement important ou une révélation approche.", affirmation: "Je suis ouvert(e) aux révélations et à la sagesse divine.", keywords: ["mystères", "magie", "sagesse", "révélation", "spiritualité"], color: "#9400D3", crystal: "Labradorite", chakra: "Troisième œil", emoji: "🌀" },
  { id: "sandalphon", number: 14, name: "Sandalphon", theme: "Prières & Musique", message: "Vos prières ont été entendues et sont en cours d'exaucement.", guidance: "Sandalphon, le frère jumeau de Métatron, transporte vos prières jusqu'au Ciel. Il est aussi l'ange de la musique. Vos intentions ont été reçues — faites confiance au timing divin.", affirmation: "Mes prières sont entendues et l'univers répond.", keywords: ["prières", "musique", "manifestation", "confiance", "timing divin"], color: "#DEB887", crystal: "Turquoise", chakra: "Gorge", emoji: "🎵" },
  { id: "thuriel", number: 15, name: "Thuriel", theme: "Animaux & Nature", message: "Les animaux vous envoient des messages. Observez-les.", guidance: "Thuriel veille sur les animaux et la nature sauvage. Si un animal attire votre attention, c'est un messager. Reconnectez-vous à la nature pour trouver les réponses que vous cherchez.", affirmation: "Je suis en harmonie avec tous les êtres vivants.", keywords: ["animaux", "nature", "messages", "harmonie", "connexion"], color: "#8B4513", crystal: "Jaspe brun", chakra: "Racine", emoji: "🦋" },
  { id: "uriel", number: 16, name: "Uriel", theme: "Sagesse & Idées", message: "Les idées brillantes vous sont transmises. Notez-les.", guidance: "Uriel, l'ange de la sagesse et de la lumière intellectuelle, illumine votre esprit avec des idées innovantes et des solutions créatives. Soyez attentif(ve) aux pensées qui surgissent — elles viennent du divin.", affirmation: "Ma sagesse intérieure m'éclaire et guide mes décisions.", keywords: ["sagesse", "idées", "solutions", "clarté mentale", "illumination"], color: "#FFF176", crystal: "Ambre", chakra: "Plexus solaire", emoji: "💡" },
  { id: "zadkiel", number: 17, name: "Zadkiel", theme: "Pardon & Compassion", message: "Le pardon vous libère. Vous n'avez rien à porter.", guidance: "Zadkiel, l'ange de la flamme violette et du pardon, vous aide à vous libérer des rancœurs et des blessures passées. Le pardon n'excuse pas — il vous libère. Invoquez la flamme violette pour transmuter toute énergie négative.", affirmation: "Je me libère par le pardon et accueille la paix.", keywords: ["pardon", "compassion", "libération", "flamme violette", "guérison"], color: "#8B00FF", crystal: "Améthyste", chakra: "Couronne", emoji: "🔮" },
  { id: "sachiel", number: 18, name: "Sachiel", theme: "Abondance & Jupiter", message: "L'abondance divine coule vers vous dans toutes les directions.", guidance: "Sachiel, ange de Jupiter et de l'abondance, ouvre les portes de la prospérité spirituelle et matérielle. Il gouverne la générosité, la croissance et l'expansion. Faites confiance au flux d'abondance qui s'écoule naturellement vers vous.", affirmation: "Je reçois l'abondance divine avec gratitude et ouverture.", keywords: ["abondance", "Jupiter", "prospérité", "expansion", "générosité"], color: "#4169E1", crystal: "Saphir bleu", chakra: "Gorge", emoji: "🌊" },
  { id: "aniel", number: 19, name: "Aniel", theme: "Courage & Renouveau", message: "Votre courage intérieur brise les vieux cycles et ouvre l'avenir.", guidance: "Aniel, ange du courage et de la rupture des habitudes répétitives, vous aide à briser les schémas limitants. Il vous donne la force de recommencer, de renouveler votre approche et de dépasser les situations qui semblaient figées.", affirmation: "J'ai le courage de renouveler ma vie et de dépasser mes limites.", keywords: ["courage", "renouveau", "rupture", "libération", "force"], color: "#FFD700", crystal: "Quartz doré", chakra: "Plexus solaire", emoji: "🌅" },
  { id: "habuhiah", number: 20, name: "Habuhiah", theme: "Guérison & Fertilité", message: "La guérison et la fertilité sont actives dans votre vie.", guidance: "Habuhiah, ange de la guérison et de la fertilité, veille sur la santé, la fécondité et l'harmonie entre l'être et la nature. Il favorise les guérisons sur tous les plans et bénit les nouvelles créations, qu'elles soient physiques ou artistiques.", affirmation: "Mon corps et mon être se guérissent et s'épanouissent.", keywords: ["guérison", "fertilité", "santé", "nature", "harmonie"], color: "#90EE90", crystal: "Jade vert", chakra: "Sacré", emoji: "🌱" },
  { id: "virtue", number: 21, name: "Les Vertus", theme: "Miracles & Phénomènes Naturels", message: "Les miracles sont naturels. Attendez-vous à l'extraordinaire.", guidance: "Le chœur des Vertus gouverne les miracles et les phénomènes naturels selon la hiérarchie céleste de Pseudo-Denys l'Aréopagite. Ces anges vous rappellent que les miracles ne sont pas des exceptions — ils sont la norme quand on vit en alignement avec son âme. Ouvrez-vous à l'impossible.", affirmation: "Les miracles sont ma réalité quotidienne.", keywords: ["miracles", "merveilles", "alignement", "magie", "extraordinaire"], color: "#40E0D0", crystal: "Aigue-marine", chakra: "Gorge", emoji: "🌈" },
  { id: "power", number: 22, name: "Les Puissances", theme: "Courage & Protection Céleste", message: "Vous avez la force d'avancer. Passez à l'action maintenant.", guidance: "Le chœur des Puissances veille sur l'ordre du cosmos et vous donne la force et le courage nécessaires pour réaliser vos rêves. Cessez de reporter — le moment est maintenant. L'univers vous soutient dans chaque pas audacieux que vous faites.", affirmation: "J'agis avec courage et confiance dans ma propre puissance.", keywords: ["courage", "action", "force", "décision", "accomplissement"], color: "#FF4500", crystal: "Jaspe rouge", chakra: "Racine", emoji: "⚡" },
  { id: "principality", number: 23, name: "Les Principautés", theme: "Humanité & Planète", message: "Votre contribution à ce monde compte plus que vous ne le pensez.", guidance: "Le chœur des Principautés veille sur les nations, les villes et les communautés. Ces anges vous encouragent à contribuer à un monde meilleur, à votre échelle. Même un sourire, même un geste de bienveillance — tout compte.", affirmation: "Ma présence sur Terre est un cadeau pour le monde.", keywords: ["humanité", "contribution", "planète", "communauté", "sens"], color: "#228B22", crystal: "Malachite", chakra: "Cœur", emoji: "🌍" },
  { id: "shekinah", number: 24, name: "Shekinah", theme: "Présence Divine Féminine", message: "La présence divine féminine en vous s'éveille.", guidance: "La Shekinah est la présence divine immanente dans la tradition judaïque et kabbalistique — l'aspect féminin du divin, associé à la sefira Malkhut. Elle vous invite à honorer votre intuition, votre créativité et votre force douce. Le sacré féminin en vous est une source de sagesse infinie.", affirmation: "J'honore la sagesse divine féminine en moi.", keywords: ["divin féminin", "présence divine", "sagesse", "Kabbale", "création"], color: "#FF69B4", crystal: "Quartz rose étoilé", chakra: "Cœur", emoji: "🌸" },
  { id: "seraphiel", number: 25, name: "Séraphiel", theme: "Amour Pur & Élévation", message: "Vous êtes aimé(e) inconditionnellement par l'univers.", guidance: "Séraphiel est le chef des Séraphins, les anges les plus proches de la Source divine. Il vous transmet l'amour pur et inconditionnel de l'univers. Vous n'avez rien à prouver — vous êtes aimé(e) tel(le) que vous êtes.", affirmation: "Je suis aimé(e) inconditionnellement et totalement.", keywords: ["amour pur", "élévation", "divin", "inconditionnalité", "lumière"], color: "#FF0000", crystal: "Rubis", chakra: "Couronne", emoji: "❤️" },
  { id: "cassiel", number: 26, name: "Cassiel", theme: "Patience & Karma", message: "Tout arrive au bon moment. Faites confiance au timing.", guidance: "Cassiel, l'ange du temps et du karma, vous enseigne la patience et la confiance dans le timing divin. Ce que vous avez semé porte ses fruits. Continuez à agir avec intégrité — le karma est votre allié.", affirmation: "Je fais confiance au parfait timing de l'univers.", keywords: ["patience", "karma", "timing", "intégrité", "cycles"], color: "#708090", crystal: "Obsidienne", chakra: "Racine", emoji: "⏳" },
  { id: "anael", number: 27, name: "Anaël", theme: "Amour Romantique & Beauté", message: "L'amour romantique vous est destiné. Ouvrez votre cœur.", guidance: "Anaël gouverne Vénus et l'amour romantique. Il vous aide à attirer et à maintenir des relations amoureuses épanouissantes. Si vous êtes en couple, c'est le moment de raviver la flamme. Si vous êtes seul(e), l'amour approche.", affirmation: "Mon cœur est prêt à accueillir l'amour véritable.", keywords: ["amour romantique", "beauté", "attraction", "Vénus", "passion"], color: "#DC143C", crystal: "Rhodonite", chakra: "Cœur", emoji: "💕" },
  { id: "barachiel", number: 28, name: "Barachiel", theme: "Chance & Bénédictions", message: "La chance vous sourit. Les bénédictions arrivent.", guidance: "Barachiel est l'ange de la chance et des bénédictions. Sa présence annonce une période de chance et de bonnes surprises. Attendez-vous à des bénédictions inattendues — restez ouvert(e) aux cadeaux de l'univers.", affirmation: "Je reçois les bénédictions de l'univers avec gratitude.", keywords: ["chance", "bénédictions", "surprise", "gratitude", "abondance"], color: "#FFFF00", crystal: "Citrine", chakra: "Plexus solaire", emoji: "🍀" },
  { id: "camael", number: 29, name: "Camaël", theme: "Force & Mars", message: "Votre force intérieure est plus grande que vous ne le pensez.", guidance: "Camaël gouverne Mars et la force martiale — mais aussi la guérison par la force. Il vous aide à surmonter les obstacles et à vous défendre avec sagesse. La combativité juste est une vertu.", affirmation: "Je puise dans ma force profonde pour dépasser mes défis.", keywords: ["force", "Mars", "courage", "obstacle", "dépassement"], color: "#B22222", crystal: "Jaspe rouge", chakra: "Racine", emoji: "🛡️" },
  { id: "cherubiel", number: 30, name: "Chérubiel", theme: "Amour Divin & Connaissance", message: "La sagesse du cœur vous guide vers la vérité.", guidance: "Chérubiel, chef des Chérubins, vous ouvre l'accès à la connaissance divine et à l'amour pur. Il garde les secrets sacrés et les révèle à ceux qui vibrent dans l'amour et la vérité.", affirmation: "Mon cœur et mon esprit s'unissent dans la sagesse.", keywords: ["amour divin", "connaissance", "sagesse", "vérité", "cœur"], color: "#4682B4", crystal: "Saphir", chakra: "Troisième œil", emoji: "📚" },
  { id: "damabiah", number: 31, name: "Damabiah", theme: "Eau & Purification", message: "Purifiez votre énergie et laissez couler le renouveau.", guidance: "Damabiah gouverne l'élément eau et la purification émotionnelle. Prenez un bain de sel, buvez de l'eau consciente, allez près d'un cours d'eau. Laissez l'eau emporter ce qui ne vous appartient plus.", affirmation: "Je me purifie et m'ouvre au renouveau.", keywords: ["eau", "purification", "guérison", "émotions", "flux"], color: "#00CED1", crystal: "Aigue-marine", chakra: "Sacré", emoji: "💧" },
  { id: "elemiah", number: 32, name: "Élémiah", theme: "Voyages & Karma Professionnel", message: "Un voyage ou un changement professionnel s'annonce.", guidance: "Élémiïah gouverne les voyages intérieurs et extérieurs ainsi que le karma professionnel. Si vous cherchez votre voie professionnelle, des révélations arrivent. Un déplacement ou changement de cap s'approche.", affirmation: "Je suis guidé(e) vers ma juste voie professionnelle.", keywords: ["voyage", "carrière", "changement", "karma", "direction"], color: "#FF8C00", crystal: "Calcite orange", chakra: "Plexus solaire", emoji: "✈️" },
  { id: "hahasiah", number: 33, name: "Hahasiah", theme: "Médecine Universelle", message: "La guérison universelle est à votre portée.", guidance: "Hahasiah révèle les secrets de la médecine universelle et des remèdes cachés dans la nature. Si vous traversez une période de maladie, des solutions alternatives ou une guérison miraculeuse peuvent se manifester.", affirmation: "Mon corps possède une sagesse de guérison infinie.", keywords: ["guérison universelle", "médecine", "nature", "santé", "remèdes"], color: "#32CD32", crystal: "Jade", chakra: "Cœur", emoji: "🌿" },
  { id: "imamiah", number: 34, name: "Imamiah", theme: "Liberté & Voyages", message: "Libérez-vous de toute prison mentale ou physique.", guidance: "Imamiah gouverne la liberté sous toutes ses formes. Si vous vous sentez enfermé(e) — dans une relation, un travail, une croyance — cet ange vous aide à retrouver votre liberté essentielle avec honneur et dignité.", affirmation: "Je suis libre de créer la vie que mon âme désire.", keywords: ["liberté", "voyage", "émancipation", "dignité", "renouveau"], color: "#FF6347", crystal: "Cornaline", chakra: "Sacré", emoji: "🦅" },
  { id: "jeliel", number: 35, name: "Jéliel", theme: "Amour Conjugal & Fidélité", message: "L'amour véritable est fidèle et résiste à toutes les épreuves.", guidance: "Jéliel est l'ange de l'amour conjugal et de la fidélité. Il aide à maintenir la flamme et la loyauté dans les relations durables. Si vous traversez une crise de couple, demandez son aide pour retrouver la complicité originelle.", affirmation: "Mon amour est profond, stable et fidèle.", keywords: ["amour conjugal", "fidélité", "couple", "durabilité", "complicité"], color: "#C71585", crystal: "Grenat", chakra: "Sacré", emoji: "💍" },
  { id: "lelahel", number: 36, name: "Lélahe", theme: "Lumière & Célébrité", message: "Votre lumière mérite d'être vue. Ne vous cachez plus.", guidance: "Lélahe vous encourage à sortir de l'ombre et à rayonner publiquement. Que ce soit dans votre carrière, vos relations ou vos projets créatifs, il est temps de vous montrer tel(le) que vous êtes vraiment.", affirmation: "Je laisse briller ma lumière sans retenue.", keywords: ["lumière", "visibilité", "rayonnement", "créativité", "confiance"], color: "#FFD700", crystal: "Sunstone", chakra: "Plexus solaire", emoji: "🌟" },
  { id: "mahasiah", number: 37, name: "Mahasiah", theme: "Paix & Rectification", message: "La paix est possible. Il n'est jamais trop tard pour rectifier.", guidance: "Mahasiah vous aide à corriger les erreurs passées et à trouver la paix. Si vous avez des regrets, il n'est jamais trop tard pour réparer ou pour vous pardonner. La rectification est une forme de croissance spirituelle.", affirmation: "Je rectifie avec grâce et retrouve la paix intérieure.", keywords: ["paix", "rectification", "pardon", "réparation", "harmonie"], color: "#87CEEB", crystal: "Célestite", chakra: "Gorge", emoji: "☮️" },
  { id: "mihael", number: 38, name: "Mihaël", theme: "Fertilité & Fidélité", message: "La création et la fertilité sont actives dans votre vie.", guidance: "Mihaël gouverne la fertilité — physique et créative. Si vous désirez concevoir un enfant ou un projet, son énergie favorise la fécondité. Il renforce aussi la fidélité et la confiance dans les relations.", affirmation: "Je suis fertile de projets, d'idées et d'amour.", keywords: ["fertilité", "création", "fidélité", "confiance", "nouveau"], color: "#90EE90", crystal: "Jade vert", chakra: "Sacré", emoji: "🌱" },
  { id: "mumiah", number: 39, name: "Mumiah", theme: "Fin de Cycles & Renaissance", message: "Un cycle se clôture pour qu'un nouveau puisse naître.", guidance: "Mumiah gouverne les fins et les renouveaux. Si vous vivez une fin difficile, sachez qu'elle prépare une renaissance magnifique. Faites confiance à ce cycle de mort et de renaissance — il est sacré.", affirmation: "Je lâche le passé avec gratitude et j'accueille mon renouveau.", keywords: ["fin de cycle", "renaissance", "renouveau", "transformation", "confiance"], color: "#2F4F4F", crystal: "Labradorite", chakra: "Couronne", emoji: "🔄" },
  { id: "nanael", number: 40, name: "Nanaël", theme: "Connaissance Spirituelle", message: "Un enseignement spirituel important s'offre à vous.", guidance: "Nanaël est l'ange de la connaissance spirituelle supérieure. Il vous connecte aux maîtres ascensionnés et aux enseignements ésotériques. Une rencontre ou un livre important pourrait changer votre vision.", affirmation: "Je suis ouvert(e) à la sagesse universelle.", keywords: ["connaissance", "spiritualité", "enseignement", "maîtres", "ésotérisme"], color: "#4B0082", crystal: "Améthyste", chakra: "Couronne", emoji: "📖" },
  { id: "nithael", number: 41, name: "Nithaël", theme: "Légitimité & Héritage", message: "Vous méritez pleinement ce que vous recevez.", guidance: "Nithaël vous aide à vous sentir légitime dans vos succès et vos héritages. Si vous avez du mal à vous sentir méritant(e), il dissout les croyances limitantes sur ce que vous valez et ce que vous méritez.", affirmation: "Je mérite la réussite, l'amour et l'abondance.", keywords: ["légitimité", "mérite", "héritage", "confiance en soi", "valeur"], color: "#B8860B", crystal: "Pyrite", chakra: "Plexus solaire", emoji: "👑" },
  { id: "omael", number: 42, name: "Omaël", theme: "Patience & Règne Végétal", message: "Tout grandit en son temps. Faites confiance au processus.", guidance: "Omaël enseigne la patience à travers les cycles naturels de la nature. Comme une graine qui germe dans le noir, vos projets ont besoin de temps pour s'épanouir. Ne forcez pas — nourrissez.", affirmation: "Je fais confiance au temps et au processus naturel de croissance.", keywords: ["patience", "croissance", "nature", "végétal", "processus"], color: "#228B22", crystal: "Péridot", chakra: "Cœur", emoji: "🌳" },
  { id: "poiel", number: 43, name: "Poïel", theme: "Fortune & Renommée", message: "Le succès et la reconnaissance arrivent dans votre vie.", guidance: "Poïel gouverne la fortune, la renommée et le soutien universel. Si vous cherchez à développer votre visibilité ou votre prospérité, son énergie amplifie vos efforts et attire les bonnes opportunités.", affirmation: "Je reçois le succès et la reconnaissance qui me correspondent.", keywords: ["fortune", "succès", "renommée", "visibilité", "opportunité"], color: "#FFD700", crystal: "Citrine", chakra: "Plexus solaire", emoji: "🏆" },
  { id: "seheiah", number: 44, name: "Séheïah", theme: "Longévité & Protection", message: "Vous êtes protégé(e) des accidents et des maladies.", guidance: "Séheïah est l'ange de la longévité et de la protection contre les accidents, les maladies et les catastrophes. Sa présence dans votre tirage est un signe de protection divine active autour de vous.", affirmation: "Je vis dans la protection divine et la pleine santé.", keywords: ["longévité", "protection", "santé", "sécurité", "guérison"], color: "#00FA9A", crystal: "Jade", chakra: "Racine", emoji: "🛡️" },
];

export interface AngelSpread {
  id: string;
  name: string;
  count: number;
  positions: string[];
  description: string;
}

export const ANGEL_SPREADS: AngelSpread[] = [
  { id: "ange-unique", name: "Message du Jour", count: 1, positions: ["Message de votre Ange gardien"], description: "Votre ange gardien vous transmet son message du jour." },
  { id: "ange-trinite", name: "Trinité des Anges", count: 3, positions: ["Ce que l'univers vous offre", "Ce qu'on vous demande de lâcher", "L'ange qui vous guide"], description: "Trois anges révèlent les forces à l'œuvre dans votre vie." },
  { id: "ange-guidance", name: "Guidance Complète", count: 4, positions: ["Situation actuelle", "Ce qui vous aide", "Ce qui vous freine", "Message divin"], description: "Une guidance complète de vos anges sur votre situation." },
  { id: "ange-amour", name: "Oracle Amoureux", count: 3, positions: ["Votre énergie en amour", "L'énergie de l'autre (ou l'amour à venir)", "Guidance de votre ange"], description: "Vos anges révèlent la vérité de votre vie amoureuse." },
  { id: "ange-annee", name: "Anges de l'Année", count: 4, positions: ["Thème de l'année", "Défi à surmonter", "Don à développer", "Bénédiction qui arrive"], description: "Quatre anges tracent le chemin de votre année." },
];

export function drawAngelCards(count: number): AngeCard[] {
  const shuffled = [...ANGEL_CARDS];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}
