export interface BellineCard {
  id: number;
  name: string;
  planet: string; // "Soleil" | "Lune" | "Mercure" | "Vénus" | "Mars" | "Jupiter" | "Saturne" | "Uranus" | "Neptune"
  keywords: string[];
  upright: string;
  element?: string;
  /** true = bénéfique (Vénus, Jupiter, Soleil) ; false = maléfique (Saturne, Mars, Neptune) ; undefined = neutre (Lune, Mercure, Uranus) */
  beneficial?: boolean;
}

export const BELLINE_DECK: BellineCard[] = [
  {
    id: 1,
    name: "Le Génie",
    planet: "Soleil",
    keywords: ["inspiration", "génie", "créativité", "révélation"],
    upright: "Une illumination intérieure vous guide vers une découverte extraordinaire qui changera le cours de votre vie.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 2,
    name: "La Destinée",
    planet: "Saturne",
    keywords: ["destin", "karma", "chemin de vie", "prédestination"],
    upright: "Le destin se manifeste avec force, révélant que certains événements étaient écrits depuis toujours dans le grand livre de votre vie.",
    element: "Terre",
    beneficial: false,
  },
  {
    id: 3,
    name: "La Lettre",
    planet: "Mercure",
    keywords: ["message", "communication", "nouvelle", "correspondance"],
    upright: "Une communication importante arrive bientôt et apportera des informations déterminantes pour votre situation actuelle.",
    element: "Air",
  },
  {
    id: 4,
    name: "Le Cadeau",
    planet: "Vénus",
    keywords: ["don", "présent", "générosité", "surprise"],
    upright: "Un cadeau inattendu, qu'il soit matériel ou spirituel, vous est offert avec amour et générosité sincère.",
    element: "Terre",
    beneficial: true,
  },
  {
    id: 5,
    name: "La Voyageuse",
    planet: "Mercure",
    keywords: ["voyage", "déplacement", "mobilité", "exploration"],
    upright: "Un déplacement ou voyage se profile à l'horizon, ouvrant de nouveaux horizons et de belles rencontres.",
    element: "Air",
  },
  {
    id: 6,
    name: "Le Chemin",
    planet: "Mercure",
    keywords: ["direction", "voie", "parcours", "progression"],
    upright: "La voie qui s'ouvre devant vous est la bonne ; avancez avec confiance sur ce chemin qui mène à votre accomplissement.",
    element: "Air",
  },
  {
    id: 7,
    name: "La Fortune",
    planet: "Jupiter",
    keywords: ["chance", "prospérité", "bonne étoile", "abondance"],
    upright: "La fortune vous sourit et une période de grande chance et d'abondance matérielle s'annonce à votre porte.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 8,
    name: "La Joie",
    planet: "Soleil",
    keywords: ["bonheur", "allégresse", "contentement", "célébration"],
    upright: "La joie pure et lumineuse illumine votre quotidien, apportant bonheur et légèreté dans tous vos domaines de vie.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 9,
    name: "La Mort",
    planet: "Saturne",
    keywords: ["transformation", "fin", "renouveau", "passage"],
    upright: "Une fin nécessaire ouvre la porte à une transformation profonde, permettant un renouveau libérateur et bienfaiteur.",
    element: "Terre",
    beneficial: false,
  },
  {
    id: 10,
    name: "La Force",
    planet: "Mars",
    keywords: ["puissance", "courage", "détermination", "vitalité"],
    upright: "Votre force intérieure et votre courage sont vos plus grands atouts pour surmonter les défis qui se présentent.",
    element: "Feu",
    beneficial: false,
  },
  {
    id: 11,
    name: "La Flatterie",
    planet: "Vénus",
    keywords: ["séduction", "compliments", "faux semblants", "charme"],
    upright: "Des paroles flatteuses circulent autour de vous ; discernez la sincérité des intentions avant d'accorder votre confiance.",
    element: "Air",
    beneficial: true,
  },
  {
    id: 12,
    name: "Le Mariage",
    planet: "Vénus",
    keywords: ["union", "engagement", "alliance", "lien sacré"],
    upright: "Une union profonde et durable se profile, qu'elle soit romantique, professionnelle ou spirituelle, scellant un beau destin commun.",
    element: "Eau",
    beneficial: true,
  },
  {
    id: 13,
    name: "La Trahison",
    planet: "Neptune",
    keywords: ["trahison", "mensonge", "déception", "illusion"],
    upright: "Une trahison ou une déception amère se cache dans votre entourage ; restez vigilant et protégez vos confidences précieuses.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 14,
    name: "La Surprise",
    planet: "Uranus",
    keywords: ["imprévu", "surprise", "révélation soudaine", "choc"],
    upright: "Un événement surprenant et inattendu bouleverse votre quotidien, apportant un changement radical et souvent bénéfique.",
    element: "Air",
  },
  {
    id: 15,
    name: "Le Profit",
    planet: "Jupiter",
    keywords: ["gain", "bénéfice", "récompense", "avantage"],
    upright: "Un profit matériel ou intellectuel significatif récompense vos efforts et vos investissements passés avec générosité.",
    element: "Terre",
    beneficial: true,
  },
  {
    id: 16,
    name: "La Visite",
    planet: "Lune",
    keywords: ["visite", "arrivée", "rencontre", "invité"],
    upright: "Une visite ou rencontre imminente apportera de l'émotion et du changement dans votre sphère personnelle ou professionnelle.",
    element: "Eau",
  },
  {
    id: 17,
    name: "La Douleur",
    planet: "Saturne",
    keywords: ["souffrance", "épreuve", "peine", "difficulté"],
    upright: "Une épreuve douloureuse traverse votre chemin, mais sa traversée forge votre caractère et approfondit votre sagesse intérieure.",
    element: "Terre",
    beneficial: false,
  },
  {
    id: 18,
    name: "La Femme Aimée",
    planet: "Vénus",
    keywords: ["amour", "féminité", "désir", "bien-aimée"],
    upright: "La femme aimée ou une figure féminine bienveillante joue un rôle central et essentiel dans votre situation présente.",
    element: "Eau",
    beneficial: true,
  },
  {
    id: 19,
    name: "La Famille",
    planet: "Lune",
    keywords: ["famille", "racines", "héritage", "liens familiaux"],
    upright: "Les liens familiaux sont au cœur de la question et apportent soutien, chaleur et continuité dans votre vie affective.",
    element: "Eau",
  },
  {
    id: 20,
    name: "La Maison",
    planet: "Lune",
    keywords: ["foyer", "demeure", "sécurité", "habitat"],
    upright: "Le foyer et la vie domestique occupent une place centrale, promettant stabilité, sécurité et douceur du chez-soi.",
    element: "Terre",
  },
  {
    id: 21,
    name: "Le Retour",
    planet: "Lune",
    keywords: ["retour", "renaissance", "réconciliation", "recommencement"],
    upright: "Un retour bienvenu se prépare, qu'il s'agisse d'une personne, d'une situation ou d'un sentiment que vous croyiez perdu.",
    element: "Eau",
  },
  {
    id: 22,
    name: "L'Enquête",
    planet: "Mercure",
    keywords: ["recherche", "investigation", "analyse", "vérité"],
    upright: "Une investigation ou recherche approfondie s'impose pour éclairer les zones d'ombre et découvrir la vérité dissimulée.",
    element: "Air",
  },
  {
    id: 23,
    name: "La Pensée",
    planet: "Mercure",
    keywords: ["réflexion", "intellect", "idée", "méditation"],
    upright: "Une idée puissante ou une réflexion profonde guide vos décisions vers une compréhension nouvelle et éclairée.",
    element: "Air",
  },
  {
    id: 24,
    name: "La Justice",
    planet: "Saturne",
    keywords: ["équité", "vérité", "jugement", "équilibre"],
    upright: "La justice s'exercera avec équité et la vérité triomphera, rétablissant l'équilibre dans une situation longtemps perturbée.",
    element: "Air",
    beneficial: false,
  },
  {
    id: 25,
    name: "La Réussite",
    planet: "Soleil",
    keywords: ["succès", "accomplissement", "victoire", "épanouissement"],
    upright: "La réussite couronne vos efforts avec éclat et vos projets aboutissent selon vos espoirs les plus chers.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 26,
    name: "Le Médecin",
    planet: "Mercure",
    keywords: ["guérison", "soin", "conseil", "expertise"],
    upright: "Un expert ou guérisseur bienveillant apporte l'aide nécessaire pour surmonter une difficulté de santé ou de conseil.",
    element: "Terre",
  },
  {
    id: 27,
    name: "La Faveur",
    planet: "Jupiter",
    keywords: ["grâce", "protection", "bénédiction", "soutien"],
    upright: "Une faveur divine ou humaine vous est accordée, ouvrant des portes qui semblaient fermées et facilitant votre chemin.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 28,
    name: "La Plainte",
    planet: "Saturne",
    keywords: ["grief", "réclamation", "mécontentement", "conflit"],
    upright: "Un grief ou une insatisfaction profonde cherche à s'exprimer ; exprimez vos besoins avec clarté pour rétablir l'harmonie.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 29,
    name: "La Santé",
    planet: "Soleil",
    keywords: ["vitalité", "bien-être", "guérison", "forme"],
    upright: "La santé et la vitalité sont préservées ou en voie de restauration, promettant un retour à l'équilibre et à la plénitude.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 30,
    name: "L'Absurdité",
    planet: "Uranus",
    keywords: ["confusion", "chaos", "incompréhension", "désordre"],
    upright: "Une situation confuse ou absurde sème le désordre autour de vous ; restez ancré dans votre bon sens pour naviguer sereinement.",
    element: "Air",
  },
  {
    id: 31,
    name: "La Maladie",
    planet: "Saturne",
    keywords: ["maladie", "fragilité", "vulnérabilité", "affaiblissement"],
    upright: "Une période de vulnérabilité nécessite attention et soin ; écoutez les signaux de votre corps et cherchez l'aide appropriée.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 32,
    name: "Le Chagrin",
    planet: "Neptune",
    keywords: ["tristesse", "peine", "mélancolie", "affliction"],
    upright: "Un chagrin profond traverse votre âme, mais les larmes versées ouvrent la voie à une guérison émotionnelle bienveillante.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 33,
    name: "La Satisfaction",
    planet: "Vénus",
    keywords: ["contentement", "plénitude", "accomplissement", "bonheur"],
    upright: "Une profonde satisfaction intérieure vous envahit, signe que vous êtes sur la bonne voie et en harmonie avec vos valeurs.",
    element: "Eau",
    beneficial: true,
  },
  {
    id: 34,
    name: "Le Changement",
    planet: "Uranus",
    keywords: ["mutation", "transformation", "évolution", "renouveau"],
    upright: "Un changement profond et nécessaire s'opère dans votre vie, ouvrant de nouvelles perspectives inattendues et stimulantes.",
    element: "Air",
  },
  {
    id: 35,
    name: "La Nouveauté",
    planet: "Uranus",
    keywords: ["innovation", "fraîcheur", "commencement", "découverte"],
    upright: "Une nouveauté excitante fait son entrée dans votre vie, portant avec elle la promesse d'une aventure inédite et enrichissante.",
    element: "Air",
  },
  {
    id: 36,
    name: "La Hâte",
    planet: "Mars",
    keywords: ["urgence", "rapidité", "précipitation", "impatience"],
    upright: "L'urgence est réelle et l'action immédiate s'impose, mais veillez à ne pas sacrifier la qualité à la précipitation.",
    element: "Feu",
    beneficial: false,
  },
  {
    id: 37,
    name: "L'Espoir",
    planet: "Jupiter",
    keywords: ["espérance", "foi", "optimisme", "attente positive"],
    upright: "L'espoir brille avec intensité et vos attentes positives ont toutes les chances de se concrétiser dans un avenir proche.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 38,
    name: "Le Désir",
    planet: "Vénus",
    keywords: ["désir", "aspiration", "envie", "passion"],
    upright: "Un désir puissant anime votre cœur et vos aspirations profondes méritent d'être honorées et poursuivies avec ardeur.",
    element: "Feu",
    beneficial: true,
  },
  {
    id: 39,
    name: "L'Ambition",
    planet: "Mars",
    keywords: ["ambition", "objectif", "détermination", "ascension"],
    upright: "Votre ambition légitime vous propulse vers de nouveaux sommets ; canalisez cette énergie avec sagesse pour atteindre vos buts.",
    element: "Feu",
    beneficial: false,
  },
  {
    id: 40,
    name: "L'Amour",
    planet: "Vénus",
    keywords: ["amour", "passion", "tendresse", "union des cœurs"],
    upright: "L'amour sous toutes ses formes illumine votre vie et une relation sincère ou une profonde affection s'épanouit merveilleusement.",
    element: "Eau",
    beneficial: true,
  },
  {
    id: 41,
    name: "Le Conseil",
    planet: "Mercure",
    keywords: ["guidance", "conseil", "sagesse", "recommandation"],
    upright: "Un conseil avisé d'une personne expérimentée vous guidera vers la meilleure décision dans votre situation actuelle.",
    element: "Air",
  },
  {
    id: 42,
    name: "La Peur",
    planet: "Neptune",
    keywords: ["crainte", "anxiété", "blocage", "paralysie"],
    upright: "Une peur ou anxiété vous retient d'avancer ; identifiez-la avec honnêteté pour la traverser et retrouver votre liberté intérieure.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 43,
    name: "L'Ennemi",
    planet: "Mars",
    keywords: ["adversaire", "opposition", "rivalité", "obstacle humain"],
    upright: "Un adversaire ou une opposition se dresse sur votre chemin ; restez vigilant et gardez votre stratégie confidentielle.",
    element: "Feu",
    beneficial: false,
  },
  {
    id: 44,
    name: "La Richesse",
    planet: "Jupiter",
    keywords: ["prospérité", "abondance", "opulence", "succès matériel"],
    upright: "La richesse matérielle et spirituelle vous est promise, récompensant vos mérites et ouvrant une ère d'abondance durable.",
    element: "Terre",
    beneficial: true,
  },
  {
    id: 45,
    name: "La Méfiance",
    planet: "Saturne",
    keywords: ["prudence", "doute", "suspicion", "vigilance"],
    upright: "La méfiance est de mise dans cette situation ; faites confiance à votre instinct et vérifiez les apparences avant d'agir.",
    element: "Terre",
    beneficial: false,
  },
  {
    id: 46,
    name: "La Question",
    planet: "Mercure",
    keywords: ["interrogation", "incertitude", "recherche de réponse", "doute"],
    upright: "Une question importante attend sa réponse ; posez-la clairement et soyez attentif aux signes que l'univers vous envoie.",
    element: "Air",
  },
  {
    id: 47,
    name: "Le Coup de Théâtre",
    planet: "Uranus",
    keywords: ["retournement", "surprise totale", "renversement", "choc inattendu"],
    upright: "Un retournement spectaculaire et inattendu bouleverse complètement la donne, transformant radicalement votre situation en cours.",
    element: "Air",
  },
  {
    id: 48,
    name: "La Réponse",
    planet: "Mercure",
    keywords: ["réponse", "solution", "clarification", "révélation"],
    upright: "La réponse tant attendue se manifeste enfin, apportant la clarté nécessaire pour avancer sereinement sur votre chemin.",
    element: "Air",
  },
  {
    id: 49,
    name: "L'Aide",
    planet: "Jupiter",
    keywords: ["soutien", "assistance", "secours", "solidarité"],
    upright: "Une aide précieuse et bienveillante se présente au bon moment, vous permettant de surmonter un obstacle avec grâce.",
    element: "Terre",
    beneficial: true,
  },
  {
    id: 50,
    name: "La Tristesse",
    planet: "Neptune",
    keywords: ["mélancolie", "deuil", "abattement", "isolement"],
    upright: "Une vague de tristesse traverse votre cœur ; accordez-vous le droit à l'émotion car elle porte les graines d'une guérison profonde.",
    element: "Eau",
    beneficial: false,
  },
  {
    id: 51,
    name: "Le Mouvement",
    planet: "Mercure",
    keywords: ["action", "dynamisme", "progression", "activité"],
    upright: "Le mouvement s'accélère autour de vous et il est temps d'agir avec dynamisme pour saisir les opportunités en mouvement.",
    element: "Air",
  },
  {
    id: 52,
    name: "Le Temps",
    planet: "Saturne",
    keywords: ["patience", "durée", "cycles", "maturité"],
    upright: "Le temps est votre allié dans cette situation ; la patience et la persévérance apporteront les fruits attendus en leur heure.",
    element: "Terre",
    beneficial: false,
  },
  {
    id: 53,
    name: "La Célébration",
    planet: "Soleil",
    keywords: ["fête", "victoire", "reconnaissance", "joie collective"],
    upright: "Une célébration bien méritée s'annonce, marquant le couronnement de vos efforts et le partage de votre bonheur avec vos proches.",
    element: "Feu",
    beneficial: true,
  },
];

export interface BellineSpread {
  id: string;
  name: string;
  count: number;
  positions: string[];
  description: string;
}

export const BELLINE_SPREADS: BellineSpread[] = [
  {
    id: "reponse",
    name: "La Réponse",
    count: 1,
    positions: ["La réponse de l'Oracle"],
    description: "Une carte pour une réponse directe et précise de l'Oracle.",
  },
  {
    id: "trilogie",
    name: "La Trilogie Planétaire",
    count: 3,
    positions: ["Passé", "Présent", "Futur"],
    description: "Trois cartes pour une vision temporelle sous l'influence des astres.",
  },
  {
    id: "quintessence",
    name: "La Quintessence",
    count: 5,
    positions: [
      "Votre énergie",
      "L'environnement",
      "Ce qui vient",
      "L'obstacle",
      "La résolution",
    ],
    description: "Cinq cartes pour une lecture approfondie de votre situation.",
  },
  {
    id: "grand-oracle",
    name: "Le Grand Oracle",
    count: 7,
    positions: [
      "Situation actuelle",
      "Influences passées",
      "Influences futures",
      "Vos atouts",
      "Vos obstacles",
      "Le conseil planétaire",
      "Le dénouement",
    ],
    description: "Sept cartes pour une révélation complète des forces en jeu.",
  },
  {
    id: "tirage-planetaire",
    name: "Tirage Planétaire",
    count: 7,
    positions: [
      "Soleil — Vitalité et succès",
      "Lune — Émotions et intuition",
      "Mercure — Communication",
      "Vénus — Amour et harmonie",
      "Mars — Action et conflits",
      "Jupiter — Chance et expansion",
      "Saturne — Épreuves et karma",
    ],
    description: "Les 7 planètes révèlent les forces à l'œuvre dans votre vie.",
  },
];

export function drawBelline(count: number): BellineCard[] {
  const shuffled = [...BELLINE_DECK].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
