export interface Hexagram {
  number: number;
  name: string;
  nameZh: string;
  symbol: string;
  lines: number[]; // 0=yin, 1=yang (bottom to top)
  keywords: string[];
  meaning: string;
  judgment: string;
  advice: string;
  element: string;
}

export const HEXAGRAMS: Hexagram[] = [
  { number: 1, name: "Le Créateur", nameZh: "乾 Qián", symbol: "☰☰", lines: [1,1,1,1,1,1], element: "Ciel", keywords: ["force créatrice", "initiative", "yang pur", "puissance"], meaning: "L'énergie créatrice pure et Yang. Tout ce que vous entreprendrez sera béni par le ciel.", judgment: "Le Créateur — Succès sublime. La persévérance est profitable.", advice: "Agissez avec force et conviction. Le moment est favorable pour toute initiative." },
  { number: 2, name: "Le Réceptif", nameZh: "坤 Kūn", symbol: "☷☷", lines: [0,0,0,0,0,0], element: "Terre", keywords: ["réceptivité", "douceur", "yin pur", "soutien"], meaning: "L'énergie réceptive pure et Yin. La douceur et la réceptivité portent le succès.", judgment: "Le Réceptif — Succès sublime si vous persévérez comme une jument.", advice: "Soyez réceptif et patient. Laissez les choses se développer naturellement." },
  { number: 3, name: "La Difficulté initiale", nameZh: "屯 Zhūn", symbol: "☳☵", lines: [1,0,0,1,0,0], element: "Eau/Tonnerre", keywords: ["début difficile", "désordre primordial", "croissance"], meaning: "Les débuts sont difficiles, comme une plante qui perce le sol. Persistez.", judgment: "Succès par la persévérance. Ne bougez pas seul — trouvez des alliés.", advice: "La difficulté est temporaire. Organisez-vous et trouvez du soutien." },
  { number: 4, name: "La Folie Juvénile", nameZh: "蒙 Méng", symbol: "☵☶", lines: [0,1,0,0,0,1], element: "Eau/Montagne", keywords: ["apprentissage", "inexpérience", "guidance nécessaire"], meaning: "Ignorance et apprentissage. Soyez humble et cherchez guidance.", judgment: "Succès. Ne demandez pas à l'oracle une seconde fois la même chose.", advice: "Restez ouvert à l'enseignement. La sagesse vient par l'humilité." },
  { number: 5, name: "L'Attente", nameZh: "需 Xū", symbol: "☵☰", lines: [1,1,1,0,1,0], element: "Eau/Ciel", keywords: ["attente", "patience", "nourriture", "confiance"], meaning: "L'attente nourricière. Tout vient à point à qui sait attendre.", judgment: "Sincérité et brillance. Persévérance. Traversez les grandes eaux.", advice: "Attendez le bon moment. La nourriture du corps et de l'âme est importante." },
  { number: 6, name: "Le Conflit", nameZh: "訟 Sòng", symbol: "☰☵", lines: [0,1,0,1,1,1], element: "Ciel/Eau", keywords: ["conflit", "litige", "prudence", "ne pas persévérer"], meaning: "Un conflit est en cours. Prudence et compromis sont nécessaires.", judgment: "Sincérité, danger. S'arrêter à mi-chemin porte bonheur.", advice: "Évitez les conflits inutiles. Cherchez la médiation plutôt que la victoire." },
  { number: 7, name: "L'Armée", nameZh: "師 Shī", symbol: "☷☵", lines: [0,1,0,0,0,0], element: "Terre/Eau", keywords: ["organisation", "discipline", "leadership", "soutien populaire"], meaning: "L'armée bien dirigée symbolise l'organisation disciplinée vers un but.", judgment: "Persévérance. L'homme expérimenté à la tête — pas de fautes.", advice: "Organisez vos forces. Un leadership sage amène la victoire." },
  { number: 8, name: "La Solidarité", nameZh: "比 Bǐ", symbol: "☵☷", lines: [0,0,0,1,0,0], element: "Eau/Terre", keywords: ["union", "soutien mutuel", "solidarité", "alliance"], meaning: "L'union fait la force. Cherchez des alliés et soutenez-vous mutuellement.", judgment: "Bonheur. Celui qui arrive tard sera malheureux.", advice: "Rejoignez-vous aux autres avec sincérité. L'union est votre force." },
  { number: 9, name: "La Force d'apprivoisement du petit", nameZh: "小畜 Xiǎo Chù", symbol: "☰☴", lines: [1,1,1,0,1,1], element: "Vent/Ciel", keywords: ["petits progrès", "retenue", "accumulation", "douceur"], meaning: "Les petites forces s'accumulent. Avancez doucement mais sûrement.", judgment: "Succès. Nuages denses à l'ouest, mais pas encore de pluie.", advice: "Progressez pas à pas. La douceur et la persévérance portent leurs fruits." },
  { number: 10, name: "La Marche", nameZh: "履 Lǚ", symbol: "☰☱", lines: [0,1,1,1,1,1], element: "Ciel/Lac", keywords: ["conduite appropriée", "marche sur la queue du tigre", "prudence"], meaning: "Marcher sur la queue d'un tigre — agissez avec prudence et politesse.", judgment: "Marcher sur la queue d'un tigre qui ne mord pas. Succès.", advice: "Soyez prudent et courtois. La bonne conduite ouvre toutes les portes." },
  { number: 11, name: "La Paix", nameZh: "泰 Tài", symbol: "☷☰", lines: [1,1,1,0,0,0], element: "Terre/Ciel", keywords: ["harmonie", "prospérité", "union des contraires", "épanouissement"], meaning: "Le Ciel et la Terre en union — une période de paix et de prospérité.", judgment: "Le petit part, le grand arrive. Bonheur et prospérité.", advice: "Profitez de cette période bénie. Tout est en harmonie autour de vous." },
  { number: 12, name: "La Stagnation", nameZh: "否 Pǐ", symbol: "☰☷", lines: [0,0,0,1,1,1], element: "Ciel/Terre", keywords: ["stagnation", "blocage", "désunion", "attente"], meaning: "Le Ciel et la Terre séparés — une période de stagnation et de blocage.", judgment: "Les mauvaises personnes entravent les succès. Retraite du sage.", advice: "Ne forcez pas. Retraitez-vous et attendez que les circonstances changent." },
  { number: 13, name: "La Communauté", nameZh: "同人 Tóng Rén", symbol: "☰☲", lines: [0,1,1,1,1,1], element: "Ciel/Feu", keywords: ["fraternité", "communauté", "partage", "objectif commun"], meaning: "La fraternité des humains — unissez-vous autour d'un idéal partagé.", judgment: "Communauté avec les hommes en plein air. Succès. Traversez les grandes eaux.", advice: "Rejoignez-vous à votre communauté. La force collective est insurpassable." },
  { number: 14, name: "La Grande Possession", nameZh: "大有 Dà Yǒu", symbol: "☲☰", lines: [1,1,1,1,0,1], element: "Feu/Ciel", keywords: ["abondance", "grande possession", "succès", "générosité"], meaning: "Grande abondance matérielle et spirituelle. La fortune sourit à qui est généreux.", judgment: "Succès sublime.", advice: "Partagez votre abondance avec générosité. Ce qui est partagé se multiplie." },
  { number: 15, name: "L'Humilité", nameZh: "謙 Qiān", symbol: "☷☶", lines: [0,0,0,1,0,0], element: "Terre/Montagne", keywords: ["humilité", "modestie", "équilibre", "sagesse"], meaning: "La montagne sous la Terre — la vraie grandeur se cache dans l'humilité.", judgment: "Succès. Le sage mène à terme.", advice: "L'humilité est votre plus grand atout en ce moment. Elle ouvre toutes les portes." },
  { number: 16, name: "L'Enthousiasme", nameZh: "豫 Yù", symbol: "☳☷", lines: [0,0,0,1,0,0], element: "Tonnerre/Terre", keywords: ["enthousiasme", "inspiration", "movement", "préparation"], meaning: "L'enthousiasme comme un tonnerre qui inspire tous. Moment d'agir.", judgment: "Profiter pour établir des aides et mettre l'armée en marche.", advice: "Votre enthousiasme est contagieux. Inspirez les autres et passez à l'action." },
  { number: 17, name: "Le Suivi", nameZh: "隨 Suí", symbol: "☱☳", lines: [1,0,0,0,1,1], element: "Lac/Tonnerre", keywords: ["adaptation", "suivi", "flexibilité", "accord"], meaning: "Suivre le mouvement juste — l'adaptation intelligente mène au succès.", judgment: "Succès sublime. Persévérance. Pas de faute.", advice: "Adaptez-vous à la situation. Suivre le flux naturel des choses est sage." },
  { number: 18, name: "Le Travail sur ce qui est gâté", nameZh: "蠱 Gǔ", symbol: "☶☴", lines: [0,1,1,0,0,1], element: "Montagne/Vent", keywords: ["réparation", "correction", "régénération", "héritage"], meaning: "Corriger ce qui a été gâté — un travail difficile mais nécessaire de réparation.", judgment: "Succès sublime. Traverser les grandes eaux est profitable.", advice: "Il est temps de corriger les erreurs du passé. Le travail de régénération commence." },
  { number: 19, name: "L'Approche", nameZh: "臨 Lín", symbol: "☷☱", lines: [0,0,0,0,1,1], element: "Terre/Lac", keywords: ["approche", "progression", "bienveillance", "croissance"], meaning: "Une grande force approche — accueillez ce mouvement positif.", judgment: "Succès sublime. Persévérance profitable. À la fin du 8e mois, malheur.", advice: "Agissez maintenant. Une période favorable s'ouvre — saisissez-la." },
  { number: 20, name: "La Contemplation", nameZh: "觀 Guān", symbol: "☴☷", lines: [0,0,0,0,1,1], element: "Vent/Terre", keywords: ["observation", "contemplation", "vision", "influence"], meaning: "Contempler avant d'agir — la sage observation révèle la vérité.", judgment: "Ablutions faites mais pas encore l'offrande. La confiance est sincère.", advice: "Prenez du recul et observez la situation avec clarté avant d'agir." },
  { number: 21, name: "La Morsure franche", nameZh: "噬嗑 Shì Kè", symbol: "☲☳", lines: [1,0,1,0,0,1], element: "Feu/Tonnerre", keywords: ["décision", "obstacles à surmonter", "justice", "résolution"], meaning: "Mordre à travers l'obstacle — décision ferme et justice.", judgment: "Succès. Profitable d'employer la torture.", advice: "Soyez ferme et décidé. L'obstacle doit être surmonté sans compromis." },
  { number: 22, name: "La Grâce", nameZh: "賁 Bì", symbol: "☶☲", lines: [1,0,1,1,0,0], element: "Montagne/Feu", keywords: ["grâce", "beauté", "apparence", "formes"], meaning: "La beauté et la grâce orneront le succès — soignez les formes.", judgment: "Succès. Dans les petites affaires, il est profitable d'entreprendre.", advice: "La beauté des formes est importante. Soignez votre apparence et vos relations." },
  { number: 23, name: "Le Délabrement", nameZh: "剥 Bō", symbol: "☶☷", lines: [0,0,0,0,0,1], element: "Montagne/Terre", keywords: ["déclin", "dissolution", "lâcher prise", "purification"], meaning: "Le délabrement purificateur — ce qui doit tomber laisse place au nouveau.", judgment: "Il n'est pas profitable d'aller quelque part.", advice: "Ne luttez pas contre ce qui se dissout. Le cycle de purification est nécessaire." },
  { number: 24, name: "Le Retour", nameZh: "復 Fù", symbol: "☷☳", lines: [1,0,0,0,0,0], element: "Terre/Tonnerre", keywords: ["retour", "renaissance", "recommencement", "cycle"], meaning: "Le retour de la lumière après l'obscurité — renaissance et renouveau.", judgment: "Succès. Sortir et rentrer sans problème.", advice: "Un nouveau cycle commence. Le retour de la lumière est imminent." },
  { number: 25, name: "L'Innocence", nameZh: "無妄 Wú Wàng", symbol: "☰☳", lines: [1,0,0,1,1,1], element: "Ciel/Tonnerre", keywords: ["innocence", "spontanéité", "sincérité", "naturel"], meaning: "Agir avec spontanéité et innocence — sans calcul ni artifice.", judgment: "Succès sublime. Persévérance profitable. S'il n'est pas juste, malheur.", advice: "Agissez avec sincérité et sans calcul. La spontanéité est votre force." },
  { number: 26, name: "Le Grand Apprivoisement", nameZh: "大畜 Dà Chù", symbol: "☶☰", lines: [1,1,1,1,0,0], element: "Montagne/Ciel", keywords: ["accumulation", "maîtrise", "grande retenue", "richesse intérieure"], meaning: "Accumuler la sagesse et la force — la grande retenue prélude au grand succès.", judgment: "Persévérance profitable. Ne pas manger chez soi — fortune.", advice: "Accumulez vos forces et votre sagesse. Le grand succès demande de la préparation." },
  { number: 27, name: "Les Mâchoires", nameZh: "頤 Yí", symbol: "☶☳", lines: [1,0,0,0,0,1], element: "Montagne/Tonnerre", keywords: ["nourriture", "soin de soi", "mots", "nutrition spirituelle"], meaning: "Ce dont vous vous nourrissez — corps, esprit et âme — définit qui vous devenez.", judgment: "Persévérance profitable. Observer les mâchoires et chercher sa nourriture.", advice: "Nourrissez-vous sainement, corps et âme. Faites attention à vos paroles." },
  { number: 28, name: "La Pression des grandes", nameZh: "大過 Dà Guò", symbol: "☱☴", lines: [0,1,1,1,1,0], element: "Lac/Vent", keywords: ["pression extrême", "crise", "dépassement", "chevauchement"], meaning: "La poutre plie sous le poids — une situation de crise appelle à l'action.", judgment: "La poutre faîtière se tord. Profitable d'aller quelque part.", advice: "La situation est critique mais gérable. Agissez avant que la pression ne soit trop forte." },
  { number: 29, name: "L'Abîme", nameZh: "坎 Kǎn", symbol: "☵☵", lines: [0,1,0,0,1,0], element: "Eau/Eau", keywords: ["danger", "profondeur", "courage", "persévérance dans l'adversité"], meaning: "Double abîme — danger répété qui exige courage et persévérance.", judgment: "Sincérité. Le cœur pénètre. Succès. Agir porte bonheur.", advice: "Vous traversez des eaux profondes. Gardez foi et persistez avec courage." },
  { number: 30, name: "La Clarté", nameZh: "離 Lí", symbol: "☲☲", lines: [1,0,1,1,0,1], element: "Feu/Feu", keywords: ["clarté", "lumière", "attachement", "conscience"], meaning: "Double flamme — clarté et conscience qui illuminent votre chemin.", judgment: "Persévérance profitable. Élever une vache porte bonheur.", advice: "La clarté est votre force. Laissez votre lumière intérieure guider vos décisions." },
  { number: 31, name: "L'Influence", nameZh: "咸 Xián", symbol: "☱☶", lines: [0,0,1,1,0,0], element: "Lac/Montagne", keywords: ["attraction", "influence mutuelle", "sensibilité", "courtship"], meaning: "Attraction et influence réciproque — la douceur sur la fermeté.", judgment: "Succès. Persévérance profitable. Prendre une femme est bénéfique.", advice: "L'attraction mutuelle est forte. Exprimez vos sentiments avec sensibilité." },
  { number: 32, name: "La Durée", nameZh: "恆 Héng", symbol: "☳☴", lines: [0,1,1,1,0,0], element: "Tonnerre/Vent", keywords: ["durée", "constance", "persévérance", "mariage"], meaning: "Ce qui dure — la constance et la persévérance sont les clés du succès.", judgment: "Succès. Pas de fautes. Persévérance profitable. Aller quelque part est bénéfique.", advice: "Restez constant et fidèle à vos engagements. La durée est votre plus grande force." },
  { number: 33, name: "La Retraite", nameZh: "遯 Dùn", symbol: "☰☶", lines: [0,0,1,1,1,1], element: "Ciel/Montagne", keywords: ["retraite stratégique", "recul", "évitement sage", "préservation"], meaning: "La retraite stratégique — savoir se retirer est une grande sagesse.", judgment: "Succès. La persévérance dans les petites choses est profitable.", advice: "Ce n'est pas le moment de forcer. Retraitez-vous avec sagesse pour mieux revenir." },
  { number: 34, name: "La Grande Vigueur", nameZh: "大壯 Dà Zhuàng", symbol: "☳☰", lines: [1,1,1,1,0,0], element: "Tonnerre/Ciel", keywords: ["grande force", "vigueur", "puissance", "responsabilité du fort"], meaning: "Grande force et vigueur — usez-en avec sagesse et responsabilité.", judgment: "Persévérance profitable.", advice: "Vous êtes dans une période de grande force. Usez de votre puissance avec sagesse." },
  { number: 35, name: "Le Progrès", nameZh: "晉 Jìn", symbol: "☲☷", lines: [0,0,0,1,0,1], element: "Feu/Terre", keywords: ["progrès", "avancement", "promotion", "clarté croissante"], meaning: "Le progrès comme le soleil qui s'élève — avancez avec confiance.", judgment: "Le prince Kang offre beaucoup de chevaux. Le roi lui accorde trois audiences.", advice: "Un progrès clair et rapide est possible. Avancez avec confiance et transparence." },
  { number: 36, name: "L'Assombrissement de la lumière", nameZh: "明夷 Míng Yí", symbol: "☷☲", lines: [1,0,1,0,0,0], element: "Terre/Feu", keywords: ["obscurcissement", "adversité", "persévérance dans l'ombre", "sagesse cachée"], meaning: "Lumière obscurcie — dissimulation sage de sa lumière en temps adverses.", judgment: "Persévérance dans la difficulté, profitable.", advice: "Cachez votre lumière pour vous protéger. Persévérez discrètement en temps difficiles." },
  { number: 37, name: "La Famille", nameZh: "家人 Jiā Rén", symbol: "☴☲", lines: [1,0,1,0,1,0], element: "Vent/Feu", keywords: ["famille", "communauté", "rôles", "harmonie domestique"], meaning: "La famille bien organisée — harmonie des rôles et des relations.", judgment: "Persévérance de la femme profitable.", advice: "Soignez vos relations familiales. L'harmonie du foyer rayonne sur tout le reste." },
  { number: 38, name: "L'Opposition", nameZh: "睽 Kuí", symbol: "☲☱", lines: [0,1,1,1,0,1], element: "Feu/Lac", keywords: ["opposition", "divergence", "malentendus", "polarité"], meaning: "Opposition et divergence — dans les petites choses seulement, avancez.", judgment: "Dans les petites choses, chance.", advice: "Les grandes entreprises sont défavorables en ce moment. Concentrez-vous sur les détails." },
  { number: 39, name: "L'Obstruction", nameZh: "蹇 Jiǎn", symbol: "☵☶", lines: [0,1,0,1,0,0], element: "Eau/Montagne", keywords: ["obstacle", "immobilité", "introspection", "aide extérieure"], meaning: "Obstructions et difficultés — le moment de se retourner vers soi et chercher de l'aide.", judgment: "Profitable vers le sud-ouest, défavorable vers le nord-est.", advice: "Face aux obstacles, faites appel à vos alliés et regardez vers l'intérieur." },
  { number: 40, name: "La Libération", nameZh: "解 Xiè", symbol: "☳☵", lines: [0,1,0,1,0,0], element: "Tonnerre/Eau", keywords: ["libération", "délivrance", "résolution", "retour à la normale"], meaning: "La délivrance après l'épreuve — libérez-vous de ce qui vous entrave.", judgment: "Profitable vers le sud-ouest. S'il n'y a pas d'affaires, revenir porte bonheur.", advice: "La libération est proche. Pardonnez, lâchez prise et tournez la page." },
  { number: 41, name: "La Diminution", nameZh: "損 Sǔn", symbol: "☶☱", lines: [1,1,0,0,0,1], element: "Montagne/Lac", keywords: ["diminution", "sacrifice", "simplicité", "don de soi"], meaning: "Diminuer pour augmenter — le sacrifice consenti mène à la croissance.", judgment: "Sincérité. Chance suprême. Pas de faute. Persévérance.", advice: "Réduire, simplifier et sacrifier le superflu. La croissance viendra de la simplicité." },
  { number: 42, name: "L'Augmentation", nameZh: "益 Yì", symbol: "☴☳", lines: [1,0,0,0,1,1], element: "Vent/Tonnerre", keywords: ["augmentation", "croissance", "don généreux", "profit"], meaning: "Augmentation et croissance — une période de profit et d'expansion.", judgment: "Profitable d'entreprendre quelque chose. Traverser les grandes eaux.", advice: "Agissez maintenant — la période est favorable à toute expansion et croissance." },
  { number: 43, name: "La Percée", nameZh: "夬 Guài", symbol: "☱☰", lines: [0,1,1,1,1,1], element: "Lac/Ciel", keywords: ["percée", "détermination", "élimination du négatif", "résolution"], meaning: "Percée décisive — éliminez ce qui est nuisible avec fermeté.", judgment: "Annoncer à la cour du roi. Sincérité. Danger. Pas de confiance.", advice: "Soyez ferme et détermniné. Éliminez ce qui nuit à votre progression." },
  { number: 44, name: "La Rencontre", nameZh: "姤 Gòu", symbol: "☰☴", lines: [1,1,1,1,1,0], element: "Ciel/Vent", keywords: ["rencontre fortuite", "tentation", "attention aux apparences"], meaning: "Rencontre inattendue — attention aux tentations et aux apparences trompeuses.", judgment: "La femme est puissante. Ne pas prendre une telle femme.", advice: "Méfiez-vous des apparences séduisantes. Tout ce qui brille n'est pas or." },
  { number: 45, name: "Le Rassemblement", nameZh: "萃 Cuì", symbol: "☱☷", lines: [0,0,0,1,1,0], element: "Lac/Terre", keywords: ["rassemblement", "assemblée", "unification", "force collective"], meaning: "Rassemblement des forces — l'union crée une puissance irrésistible.", judgment: "Le roi approche son temple. Profitable de voir le grand homme.", advice: "Rassemblez vos forces et vos alliés. La puissance collective est votre atout." },
  { number: 46, name: "La Poussée vers le Haut", nameZh: "升 Shēng", symbol: "☷☴", lines: [0,0,0,0,1,1], element: "Terre/Vent", keywords: ["ascension", "progrès graduel", "montée", "effort patient"], meaning: "La montée progressive et sûre — ascension par l'effort patient et constant.", judgment: "Succès sublime. Voir le grand homme. Pas d'anxiété. Marcher vers le sud.", advice: "Progressez lentement mais sûrement vers vos objectifs. L'ascension prend du temps." },
  { number: 47, name: "L'Épuisement", nameZh: "困 Kùn", symbol: "☱☵", lines: [0,1,0,1,1,0], element: "Lac/Eau", keywords: ["épuisement", "adversité", "persévérance", "ressources limitées"], meaning: "Épuisement et privation — persévérez, la sortie de cette épreuve forge le caractère.", judgment: "Succès. Persévérance. La grande personne a de la chance.", advice: "Conservez votre énergie. Les paroles ne servent à rien — seules les actions comptent." },
  { number: 48, name: "Le Puits", nameZh: "井 Jǐng", symbol: "☵☴", lines: [0,1,0,0,1,1], element: "Eau/Vent", keywords: ["ressource inépuisable", "source", "nourrissement", "structure"], meaning: "Le puits — une source inépuisable de nourrissement est à votre disposition.", judgment: "On change la ville, pas le puits. Pas de perte, pas de gain.", advice: "Accédez à la source profonde de sagesse et de ressources qui est en vous." },
  { number: 49, name: "La Révolution", nameZh: "革 Gé", symbol: "☱☲", lines: [0,1,1,1,0,0], element: "Lac/Feu", keywords: ["révolution", "transformation", "changement radical", "renouveau"], meaning: "Révolution et transformation radicale — le changement est inévitable et nécessaire.", judgment: "En votre propre jour, sincérité. Succès sublime. Persévérance profitable.", advice: "Le moment du grand changement est arrivé. Embrassez la transformation avec courage." },
  { number: 50, name: "Le Chaudron", nameZh: "鼎 Dǐng", symbol: "☲☴", lines: [1,0,1,1,0,1], element: "Feu/Vent", keywords: ["transformation", "nourriture spirituelle", "culture", "raffinement"], meaning: "Le chaudron sacré qui transforme — nourrissement spirituel et culturel.", judgment: "Succès sublime.", advice: "Nourrissez votre esprit et contribuez à la culture. La transformation est un art." },
  { number: 51, name: "L'Ébranlement", nameZh: "震 Zhèn", symbol: "☳☳", lines: [1,0,0,1,0,0], element: "Tonnerre/Tonnerre", keywords: ["choc", "éveil soudain", "peur salutaire", "réveil"], meaning: "Le tonnerre double — un choc soudain éveille et purifie.", judgment: "Succès. Le tonnerre vient — terreur. Rires ensuite. Le tonnerre terrifie cent lieues.", advice: "Un événement soudain vous réveille. Restez calme en surface, évoluez intérieurement." },
  { number: 52, name: "L'Immobilité", nameZh: "艮 Gèn", symbol: "☶☶", lines: [0,0,1,0,0,1], element: "Montagne/Montagne", keywords: ["immobilité", "méditation", "arrêt", "retour à soi"], meaning: "La montagne double — immobilité et arrêt pour la contemplation.", judgment: "Arrêt à son dos. Ne pas toucher son corps. Va dans sa cour sans voir ses gens.", advice: "Arrêtez-vous et méditez. L'immobilité intérieure est source de grande sagesse." },
  { number: 53, name: "La Progression graduelle", nameZh: "漸 Jiàn", symbol: "☴☶", lines: [0,1,1,0,1,0], element: "Vent/Montagne", keywords: ["progrès graduel", "développement lent", "mariage", "patience"], meaning: "La progression lente comme l'oie sauvage — chaque étape est nécessaire.", judgment: "La femme est donnée en mariage — chance. Persévérance profitable.", advice: "Progressez méthodiquement. Chaque étape prépare la suivante. Ne précipitez rien." },
  { number: 54, name: "La Jeune Épousée", nameZh: "歸妹 Guī Mèi", symbol: "☳☱", lines: [0,1,1,1,0,0], element: "Tonnerre/Lac", keywords: ["relation secondaire", "désir", "attention à l'impulsivité", "compromis"], meaning: "La jeune épousée — une relation née du désir peut créer des complications.", judgment: "Agir porte malheur. Pas de profit.", advice: "Méfiez-vous des décisions impulsives en matière de cœur. Réfléchissez avant d'agir." },
  { number: 55, name: "L'Abondance", nameZh: "豐 Fēng", symbol: "☳☲", lines: [1,0,1,1,0,0], element: "Tonnerre/Feu", keywords: ["abondance", "plénitude", "apogée", "éclat bref"], meaning: "L'abondance et la plénitude — jouissez de ce moment de grande prospérité.", judgment: "Succès. Le roi se comporte ainsi. Ne sois pas inquiet. Sois comme le soleil à midi.", advice: "Profitez de cette période d'abondance. Tout est en votre faveur — agissez maintenant." },
  { number: 56, name: "Le Voyageur", nameZh: "旅 Lǚ", symbol: "☲☶", lines: [0,0,1,1,0,1], element: "Feu/Montagne", keywords: ["voyage", "étranger", "solitude", "adaptabilité"], meaning: "Le voyageur en terre étrangère — adaptez-vous et gardez la prudence.", judgment: "Le voyageur a du succès. La persévérance du voyageur porte bonheur.", advice: "Adaptez-vous à votre environnement. Soyez prudent et discret en territoire inconnu." },
  { number: 57, name: "Le Doux", nameZh: "巽 Xùn", symbol: "☴☴", lines: [0,1,1,0,1,1], element: "Vent/Vent", keywords: ["pénétration douce", "influence subtile", "persévérance discrète", "adaptabilité"], meaning: "Le vent doux qui pénètre partout — l'influence subtile et persistante.", judgment: "Un peu de succès. Profitable d'aller quelque part. Voir le grand homme.", advice: "Agissez avec douceur et persistance. Une influence subtile vaut mieux que la force brute." },
  { number: 58, name: "La Sérénité", nameZh: "兌 Duì", symbol: "☱☱", lines: [0,1,1,0,1,1], element: "Lac/Lac", keywords: ["joie", "sérénité", "partage", "plaisir"], meaning: "Double lac — joie partagée et sérénité communicative.", judgment: "Succès. Persévérance profitable.", advice: "Partagez votre joie et votre bonne humeur. La sérénité communicative porte bonheur." },
  { number: 59, name: "La Dispersion", nameZh: "渙 Huàn", symbol: "☴☵", lines: [0,1,0,0,1,1], element: "Vent/Eau", keywords: ["dissolution", "dispersion", "résolution des blocages", "flux"], meaning: "La dispersion qui dissout les rigidités — le flux retrouve son chemin.", judgment: "Succès. Le roi approche son temple. Traverser les grandes eaux est profitable.", advice: "Laissez se dissoudre ce qui est rigide. Le retour au flux naturel est libérateur." },
  { number: 60, name: "La Limitation", nameZh: "節 Jié", symbol: "☵☱", lines: [0,1,0,0,1,1], element: "Eau/Lac", keywords: ["limitation", "modération", "frontières", "discipline"], meaning: "Les limites nécessaires — la discipline et la modération créent la durabilité.", judgment: "Succès. La limitation amère ne peut persévérer.", advice: "Établissez des limites saines et tenez-vous-y. La discipline libère plutôt qu'elle n'emprisonne." },
  { number: 61, name: "La Vérité intérieure", nameZh: "中孚 Zhōng Fú", symbol: "☴☱", lines: [0,1,1,0,0,1], element: "Vent/Lac", keywords: ["vérité intérieure", "sincérité", "confiance", "transformation"], meaning: "Vérité intérieure et sincérité — ce qui vient du cœur pénètre tout.", judgment: "Cochons et poissons. Chance. Traverser les grandes eaux est profitable.", advice: "Agissez avec une sincérité absolue. La vérité intérieure rayonne et convainc sans effort." },
  { number: 62, name: "La Prédominance du petit", nameZh: "小過 Xiǎo Guò", symbol: "☳☶", lines: [0,0,1,1,0,0], element: "Tonnerre/Montagne", keywords: ["petits excès", "attention aux détails", "humilité", "modestie"], meaning: "Les petits excès — concentrez-vous sur les détails, évitez les grandes entreprises.", judgment: "Succès. Persévérance profitable. Petites choses, pas grandes.", advice: "Concentrez-vous sur les petites choses. Le moment n'est pas aux grandes actions." },
  { number: 63, name: "Après l'Accomplissement", nameZh: "既濟 Jì Jì", symbol: "☵☲", lines: [0,1,0,1,0,1], element: "Eau/Feu", keywords: ["accomplissement", "équilibre fragile", "vigilance", "après le succès"], meaning: "Après l'accomplissement — tout est en ordre, mais la vigilance est plus nécessaire que jamais.", judgment: "Succès dans les petites choses. Persévérance profitable au début, désordre à la fin.", advice: "Vous avez accompli quelque chose d'important. Maintenant, maintenez cet équilibre avec vigilance." },
  { number: 64, name: "Avant l'Accomplissement", nameZh: "未濟 Wèi Jì", symbol: "☲☵", lines: [1,0,1,0,1,0], element: "Feu/Eau", keywords: ["transition", "presque là", "précaution", "dernier effort"], meaning: "Avant l'accomplissement — la transition est presque terminée. Dernière étape cruciale.", judgment: "Succès. Le jeune renard traverse presque. Sa queue mouille. Pas d'avantage.", advice: "Vous êtes sur le point d'achever quelque chose d'important. Soyez prudent jusqu'au bout." },
];

export function getHexagram(number: number): Hexagram {
  return HEXAGRAMS[number - 1] || HEXAGRAMS[0];
}

/** @deprecated kept for backward compatibility */
export function consultIChing(): Hexagram {
  const n = Math.floor(Math.random() * 64) + 1;
  return getHexagram(n);
}

// Returns a single line value from 3-coin toss (6=old yin, 7=young yang, 8=young yin, 9=old yang)
export function tossCoins(): 6 | 7 | 8 | 9 {
  const sum = [0,1,2].reduce((acc) => acc + (Math.random() < 0.5 ? 2 : 3), 0);
  return sum as 6 | 7 | 8 | 9;
}

// Find hexagram from 6 binary line values (0=yin, 1=yang), bottom to top
export function hexagramFromLines(lines: (0|1)[]): Hexagram {
  return HEXAGRAMS.find(h => h.lines.every((l, i) => l === lines[i])) ?? HEXAGRAMS[0];
}

// Build primary + secondary hexagram from 6 toss values
export function buildHexagrams(tosses: (6|7|8|9)[]): { primary: Hexagram; secondary: Hexagram | null; changingLines: number[] } {
  const primaryLines = tosses.map(t => (t === 7 || t === 9) ? 1 : 0) as (0|1)[];
  const changingLines = tosses.map((t, i) => t === 6 || t === 9 ? i : -1).filter(i => i >= 0);
  const primary = hexagramFromLines(primaryLines);
  let secondary: Hexagram | null = null;
  if (changingLines.length > 0) {
    const secondaryLines = primaryLines.map((l, i) => changingLines.includes(i) ? (l === 1 ? 0 : 1) : l) as (0|1)[];
    secondary = hexagramFromLines(secondaryLines);
  }
  return { primary, secondary, changingLines };
}
