export interface Crystal {
  id: string;
  name: string;
  nameEn: string;
  color: string;
  colorHex: string;
  chakra: string;
  element: string;
  planet: string;
  keywords: string[];
  properties: string;
  guidance: string;
  howToUse: string;
}

export const CRYSTALS: Crystal[] = [
  {
    id: "amethyste",
    name: "Améthyste",
    nameEn: "Amethyst",
    color: "violet",
    colorHex: "#9B59B6",
    chakra: "Troisième Œil",
    element: "Éther",
    planet: "Jupiter",
    keywords: ["intuition", "protection", "spiritualité", "clarté mentale"],
    properties: "Pierre de protection et de sagesse spirituelle, l'améthyste purifie l'esprit, calme les pensées agitées et renforce l'intuition. Elle facilite la méditation et l'éveil de la conscience supérieure.",
    guidance: "Laissez votre intuition vous guider. La réponse que vous cherchez sommeille déjà en vous, attendant d'être écoutée.",
    howToUse: "Posez sur le front en méditation ou portez en pendentif pour renforcer la clarté intuitive au quotidien.",
  },
  {
    id: "quartz-rose",
    name: "Quartz Rose",
    nameEn: "Rose Quartz",
    color: "rose",
    colorHex: "#F1948A",
    chakra: "Cœur",
    element: "Eau",
    planet: "Vénus",
    keywords: ["amour", "douceur", "guérison émotionnelle", "compassion"],
    properties: "Pierre de l'amour inconditionnel, le quartz rose ouvre le chakra du cœur, cicatrise les blessures émotionnelles et attire des relations harmonieuses. Il enseigne la douceur envers soi-même et les autres.",
    guidance: "Accueillez l'amour avec un cœur ouvert. La guérison commence par la tendresse que vous vous accordez.",
    howToUse: "Placez sur le cœur pendant 10 minutes chaque matin ou portez proche de la poitrine pour rayonner l'amour.",
  },
  {
    id: "quartz-cristal",
    name: "Quartz Cristal",
    nameEn: "Clear Quartz",
    color: "blanc transparent",
    colorHex: "#D6EAF8",
    chakra: "Couronne",
    element: "Éther",
    planet: "Soleil",
    keywords: ["amplification", "clarté", "programmation", "lumière"],
    properties: "Maître guérisseur et amplificateur universel, le quartz cristal clarifie les intentions, amplifie les énergies positives et aligne tous les chakras. Il agit comme un prisme de lumière divine.",
    guidance: "Clarifiez votre intention et l'univers amplifiera votre élan. La pureté de votre désir en détermine la puissance.",
    howToUse: "Tenez en main pendant la méditation pour amplifier vos intentions ou placez en centre d'une grille de cristaux.",
  },
  {
    id: "obsidienne-noire",
    name: "Obsidienne Noire",
    nameEn: "Black Obsidian",
    color: "noir",
    colorHex: "#1C2833",
    chakra: "Racine",
    element: "Feu",
    planet: "Pluton",
    keywords: ["protection", "ancrage", "vérité", "transformation"],
    properties: "Bouclier énergétique puissant, l'obsidienne noire repousse les énergies négatives, dissout les blocages émotionnels profonds et confronte à la vérité intérieure. Elle accompagne les transformations radicales.",
    guidance: "Regardez la vérité en face sans crainte. Ce qui est révélé peut être transformé, et la transformation vous libère.",
    howToUse: "Placez à l'entrée de votre foyer pour la protection ou tenez en main lors d'un travail d'ombre et d'introspection.",
  },
  {
    id: "citrine",
    name: "Citrine",
    nameEn: "Citrine",
    color: "jaune doré",
    colorHex: "#F4D03F",
    chakra: "Plexus Solaire",
    element: "Feu",
    planet: "Soleil",
    keywords: ["abondance", "joie", "confiance", "manifestation"],
    properties: "Pierre du soleil et de l'abondance, la citrine stimule la confiance en soi, attire la prospérité et dissout les peurs liées au manque. Elle nourrit l'optimisme et la créativité manifeste.",
    guidance: "Vous méritez l'abondance sous toutes ses formes. Ouvrez-vous à recevoir avec la même générosité que vous donnez.",
    howToUse: "Placez dans le coin finances de votre maison ou portez en bague sur la main dominante pour attirer la prospérité.",
  },
  {
    id: "lapis-lazuli",
    name: "Lapis-Lazuli",
    nameEn: "Lapis Lazuli",
    color: "bleu nuit doré",
    colorHex: "#1A5276",
    chakra: "Troisième Œil",
    element: "Éther",
    planet: "Jupiter",
    keywords: ["sagesse", "vérité", "vision", "autorité intérieure"],
    properties: "Pierre des pharaons et des sages, le lapis-lazuli éveille la vision intérieure, renforce l'expression authentique et connecte à la sagesse universelle. Il favorise la communication profonde et honnête.",
    guidance: "Votre sagesse intérieure est une boussole fiable. Faites confiance à votre vision et exprimez votre vérité avec courage.",
    howToUse: "Posez sur le front ou la gorge en méditation pour clarifier votre vision et aligner parole et pensée profonde.",
  },
  {
    id: "labradorite",
    name: "Labradorite",
    nameEn: "Labradorite",
    color: "gris irisé",
    colorHex: "#5D6D7E",
    chakra: "Troisième Œil",
    element: "Eau",
    planet: "Uranus",
    keywords: ["magie", "protection aura", "synchronicité", "transformation"],
    properties: "Pierre de la magie et de la synchronicité, la labradorite protège l'aura, éveille les dons psychiques et révèle les coïncidences significatives. Elle guide vers les transitions et les changements profonds.",
    guidance: "La magie opère dans les coulisses de votre vie. Les coïncidences que vous vivez sont des invitations de l'univers.",
    howToUse: "Portez comme bijou ou tenez en poche pour renforcer votre champ aura et accueillir les synchronicités du quotidien.",
  },
  {
    id: "malachite",
    name: "Malachite",
    nameEn: "Malachite",
    color: "vert veiné",
    colorHex: "#1E8449",
    chakra: "Cœur",
    element: "Terre",
    planet: "Vénus",
    keywords: ["transformation", "guérison émotionnelle", "croissance", "protection"],
    properties: "Pierre de transformation et de guérison du cœur, la malachite révèle et libère les schémas émotionnels répétitifs. Elle accompagne les changements profonds avec courage et encourage la croissance personnelle.",
    guidance: "Les vieux schémas sont prêts à être libérés. Accueillez le changement comme une opportunité de floraison.",
    howToUse: "Placez sur le plexus solaire ou le cœur pour libérer les blocages émotionnels, mais nettoyez-la fréquemment.",
  },
  {
    id: "turquoise",
    name: "Turquoise",
    nameEn: "Turquoise",
    color: "turquoise",
    colorHex: "#1ABC9C",
    chakra: "Gorge",
    element: "Eau",
    planet: "Neptune",
    keywords: ["communication", "protection voyageur", "guérison", "authenticité"],
    properties: "Pierre sacrée des chamans et guerriers, la turquoise protège les voyageurs, facilite la communication authentique et équilibre les énergies masculines et féminines. Elle apporte chance et protection.",
    guidance: "Parlez votre vérité avec douceur et assurance. Votre authenticité est votre protection la plus puissante.",
    howToUse: "Portez au poignet ou autour du cou pour la protection lors des voyages et la fluidité dans vos communications.",
  },
  {
    id: "oeil-de-tigre",
    name: "Œil de Tigre",
    nameEn: "Tiger's Eye",
    color: "brun doré",
    colorHex: "#D4AC0D",
    chakra: "Plexus Solaire",
    element: "Feu",
    planet: "Soleil",
    keywords: ["courage", "focus", "discernement", "force willpower"],
    properties: "Pierre du courage et de la détermination, l'œil de tigre renforce la volonté, affûte le discernement et équilibre les émotions dans l'action. Il aide à atteindre les objectifs avec clarté et persévérance.",
    guidance: "Vous avez la force et la clarté nécessaires pour avancer. Concentrez votre énergie sur l'essentiel et agissez.",
    howToUse: "Tenez en main avant une décision importante ou portez sur vous pour maintenir le focus et la détermination au quotidien.",
  },
  {
    id: "calcite-orange",
    name: "Calcite Orange",
    nameEn: "Orange Calcite",
    color: "orange",
    colorHex: "#E67E22",
    chakra: "Sacré",
    element: "Feu",
    planet: "Soleil",
    keywords: ["créativité", "joie", "vitalité", "sexualité sacrée"],
    properties: "Pierre de la joie et de la créativité, la calcite orange stimule l'énergie vitale, libère les blocages émotionnels et éveille la créativité. Elle équilibre le chakra sacré et ravive la passion pour la vie.",
    guidance: "Laissez votre créativité s'exprimer librement. La joie est votre état naturel — autorisez-vous à la vivre pleinement.",
    howToUse: "Placez sur le bas-ventre ou tenez en méditation créative pour libérer l'inspiration et relancer l'énergie vitale.",
  },
  {
    id: "pyrite",
    name: "Pyrite",
    nameEn: "Pyrite",
    color: "or métallique",
    colorHex: "#C8A951",
    chakra: "Plexus Solaire",
    element: "Terre",
    planet: "Mars",
    keywords: ["prospérité", "protection", "volonté", "action"],
    properties: "Pierre de la prospérité et de la force de caractère, la pyrite attire l'abondance matérielle, renforce la confiance en soi et offre une protection contre les énergies négatives et les manipulations.",
    guidance: "Agissez avec confiance et détermination. La prospérité récompense ceux qui osent se mettre en mouvement.",
    howToUse: "Placez sur votre bureau ou dans votre espace de travail pour attirer la réussite et maintenir une énergie proactive.",
  },
  {
    id: "selenite",
    name: "Sélénite",
    nameEn: "Selenite",
    color: "blanc nacré",
    colorHex: "#FDFEFE",
    chakra: "Couronne",
    element: "Éther",
    planet: "Lune",
    keywords: ["purification", "clarté", "connexion angélique", "paix"],
    properties: "Pierre de lumière lunaire et de purification divine, la sélénite nettoie l'aura et les autres cristaux, apporte une paix profonde et facilite la connexion avec les guides spirituels et les anges gardiens.",
    guidance: "Purifiez votre espace intérieur et laissez entrer la lumière. La paix que vous cherchez est déjà présente en vous.",
    howToUse: "Passez une baguette de sélénite autour de votre corps pour purifier l'aura ou placez-la sous l'oreiller pour des rêves lucides.",
  },
  {
    id: "fluorite-violette",
    name: "Fluorite Violette",
    nameEn: "Purple Fluorite",
    color: "violet translucide",
    colorHex: "#7D3C98",
    chakra: "Troisième Œil",
    element: "Éther",
    planet: "Mercure",
    keywords: ["concentration", "organisation", "clarté mentale", "intuition"],
    properties: "Pierre de l'ordre mental et de la clarté, la fluorite violette organise les pensées dispersées, renforce la concentration et ouvre l'intuition. Elle absorbe les énergies électromagnétiques et les tensions mentales.",
    guidance: "Clarifiez vos pensées avant d'agir. Quand votre mental est ordonné, les solutions émergent avec évidence.",
    howToUse: "Posez près de votre espace de travail ou tenez pendant l'étude pour améliorer la concentration et absorber les tensions.",
  },
  {
    id: "jaspe-rouge",
    name: "Jaspe Rouge",
    nameEn: "Red Jasper",
    color: "rouge brique",
    colorHex: "#C0392B",
    chakra: "Racine",
    element: "Terre",
    planet: "Mars",
    keywords: ["ancrage", "vitalité", "stabilité", "endurance"],
    properties: "Pierre de la terre et de l'ancrage profond, le jaspe rouge renforce la vitalité physique, stabilise les émotions et favorise l'endurance dans les épreuves. Il connecte à l'énergie nourricière de la terre.",
    guidance: "Ancrez-vous dans le présent avec confiance. Votre force est enracinée profondément — vous êtes plus solide que vous ne le croyez.",
    howToUse: "Tenez dans la main non-dominante pour l'ancrage ou placez sous les pieds pendant 5 minutes pour vous recentrer.",
  },
  {
    id: "agate-bleue",
    name: "Agate Bleue",
    nameEn: "Blue Lace Agate",
    color: "bleu pâle",
    colorHex: "#AED6F1",
    chakra: "Gorge",
    element: "Air",
    planet: "Neptune",
    keywords: ["communication douce", "calme", "confiance verbale", "expression"],
    properties: "Pierre de la communication apaisante, l'agate bleue calme l'anxiété, libère la timidité et permet d'exprimer sa vérité avec douceur et assurance. Elle apporte sérénité dans les situations conflictuelles.",
    guidance: "Vos mots ont le pouvoir de guérir et de connecter. Exprimez-vous avec douceur — votre voix mérite d'être entendue.",
    howToUse: "Portez autour du cou ou tenez avant de prendre la parole en public pour calmer le trac et fluidifier l'expression.",
  },
  {
    id: "rhodonite",
    name: "Rhodonite",
    nameEn: "Rhodonite",
    color: "rose et noir",
    colorHex: "#E8A0BF",
    chakra: "Cœur",
    element: "Terre",
    planet: "Vénus",
    keywords: ["pardon", "guérison des blessures", "amour de soi", "réconciliation"],
    properties: "Pierre du pardon et de la réconciliation, la rhodonite guérit les blessures émotionnelles anciennes, favorise le pardon de soi et des autres, et rééquilibre les émotions après des chocs affectifs douloureux.",
    guidance: "Le pardon est un cadeau que vous vous offrez. Libérez le passé avec compassion et ouvrez-vous à une nouvelle légèreté.",
    howToUse: "Portez sur le cœur ou tenez en méditation lors de travail de pardon pour faciliter la libération émotionnelle profonde.",
  },
  {
    id: "amazonite",
    name: "Amazonite",
    nameEn: "Amazonite",
    color: "vert turquoise",
    colorHex: "#45B39D",
    chakra: "Cœur",
    element: "Eau",
    planet: "Uranus",
    keywords: ["vérité", "courage", "équilibre", "espoir"],
    properties: "Pierre de la vérité courageuse et de l'espoir, l'amazonite encourage l'expression honnête, équilibre les polarités masculin-féminin et apporte un espoir serein face aux difficultés et aux contradictions intérieures.",
    guidance: "Osez dire votre vérité même quand c'est difficile. L'honnêteté ouvre des portes que le compromis maintient fermées.",
    howToUse: "Portez sur le cœur ou la gorge pour harmoniser communication et sentiments, ou placez sur les chakras lors de méditation.",
  },
  {
    id: "chrysocolle",
    name: "Chrysocolle",
    nameEn: "Chrysocolla",
    color: "bleu-vert",
    colorHex: "#2ECC71",
    chakra: "Gorge",
    element: "Eau",
    planet: "Vénus",
    keywords: ["sagesse féminine", "communication", "tranquillité", "enseignement"],
    properties: "Pierre de la sagesse féminine et de la communication sacrée, la chrysocolle apporte tranquillité dans la tempête, inspire la sagesse et encourage le partage de connaissances avec douceur et profondeur.",
    guidance: "La sagesse douce est plus puissante que la force. Partagez votre lumière et inspirez les autres par votre exemple serein.",
    howToUse: "Placez sur la gorge en méditation ou portez pour renforcer votre sagesse intuitive et faciliter l'enseignement bienveillant.",
  },
  {
    id: "tourmaline-noire",
    name: "Tourmaline Noire",
    nameEn: "Black Tourmaline",
    color: "noir",
    colorHex: "#212F3D",
    chakra: "Racine",
    element: "Terre",
    planet: "Saturne",
    keywords: ["protection absolue", "ancrage", "purification", "bouclier énergétique"],
    properties: "Bouclier énergétique par excellence, la tourmaline noire repousse toutes les énergies négatives, protège contre les vampires énergétiques et les ondes électromagnétiques, tout en ancrant profondément dans le présent.",
    guidance: "Vous êtes protégé et ancré. Posez vos frontières énergétiques avec clarté — votre espace intérieur est sacré.",
    howToUse: "Placez aux quatre coins de votre chambre ou portez en bracelet pour une protection énergétique permanente et puissante.",
  },
  {
    id: "aventurine-verte",
    name: "Aventurine Verte",
    nameEn: "Green Aventurine",
    color: "vert clair scintillant",
    colorHex: "#58D68D",
    chakra: "Cœur",
    element: "Terre",
    planet: "Mercure",
    keywords: ["chance", "opportunité", "optimisme", "croissance"],
    properties: "Pierre de la chance et des nouvelles opportunités, l'aventurine verte attire la prospérité, renforce l'optimisme et ouvre le cœur aux nouvelles possibilités. Elle favorise le leadership et la prise de risques audacieux.",
    guidance: "La chance vous sourit quand vous vous ouvrez aux possibilités. Faites confiance aux nouvelles portes qui s'ouvrent devant vous.",
    howToUse: "Portez dans la poche gauche lors d'événements importants ou placez sur votre bureau pour attirer les opportunités favorables.",
  },
  {
    id: "sodalite",
    name: "Sodalite",
    nameEn: "Sodalite",
    color: "bleu roi veiné",
    colorHex: "#2471A3",
    chakra: "Troisième Œil",
    element: "Éther",
    planet: "Jupiter",
    keywords: ["logique", "intuition", "vérité intérieure", "clarté"],
    properties: "Pierre de l'harmonie entre raison et intuition, la sodalite clarifie la pensée, renforce la confiance en son jugement intérieur et favorise la communication authentique. Elle aide à trouver sa propre vérité.",
    guidance: "Faites confiance à la fois à votre intellect et à votre ressenti. La vérité émerge quand raison et intuition collaborent.",
    howToUse: "Posez sur le troisième œil en méditation ou portez lors de réunions importantes pour clarifier votre pensée et votre expression.",
  },
  {
    id: "cornaline",
    name: "Cornaline",
    nameEn: "Carnelian",
    color: "orange-rouge",
    colorHex: "#E74C3C",
    chakra: "Sacré",
    element: "Feu",
    planet: "Mars",
    keywords: ["motivation", "courage", "créativité", "vitalité"],
    properties: "Pierre du feu de l'action et de la créativité, la cornaline ravive la motivation, donne le courage d'agir et stimule la créativité. Elle renforce la confiance et la détermination dans la poursuite des projets.",
    guidance: "L'heure de l'action a sonné. Votre passion est votre carburant — lancez-vous avec confiance et enthousiasme.",
    howToUse: "Portez en bracelet sur la main dominante ou placez sur le bas-ventre pour activer l'énergie créatrice et la motivation.",
  },
  {
    id: "unakite",
    name: "Unakite",
    nameEn: "Unakite",
    color: "rose et vert",
    colorHex: "#A3C585",
    chakra: "Cœur",
    element: "Terre",
    planet: "Vénus",
    keywords: ["équilibre", "guérison progressive", "patience", "intégration"],
    properties: "Pierre de l'équilibre et de la guérison douce, l'unakite intègre les expériences émotionnelles, harmonise le corps et l'esprit et soutient une guérison progressive et profonde. Elle favorise la croissance par la patience.",
    guidance: "La guérison est un voyage, non une destination. Chaque petit pas vers l'équilibre est une victoire à célébrer.",
    howToUse: "Tenez pendant la méditation ou placez sur le cœur pour soutenir une guérison émotionnelle progressive et intégratrice.",
  },
  {
    id: "quartz-fume",
    name: "Cristal de Roche Fumé",
    nameEn: "Smoky Quartz",
    color: "brun fumé",
    colorHex: "#7D6608",
    chakra: "Racine",
    element: "Terre",
    planet: "Saturne",
    keywords: ["ancrage", "détoxification énergétique", "protection", "lâcher-prise"],
    properties: "Pierre de la purification et de l'ancrage profond, le quartz fumé neutralise les énergies négatives, facilite le lâcher-prise des peurs et des pensées obsessionnelles, et enracine solidement dans la réalité présente.",
    guidance: "Libérez ce qui vous alourdit. L'ancrage dans le présent est votre fondation — posez vos fardeaux et respirez librement.",
    howToUse: "Placez entre vos pieds en méditation ou tenez la pointe vers le bas pour drainer et transformer les énergies lourdes.",
  },
  {
    id: "angelite",
    name: "Angélite",
    nameEn: "Angelite",
    color: "bleu ciel pâle",
    colorHex: "#85C1E9",
    chakra: "Gorge",
    element: "Éther",
    planet: "Uranus",
    keywords: ["communication angélique", "paix", "télépathie", "guidance divine"],
    properties: "Pierre de connexion avec les anges et les guides spirituels, l'angélite ouvre les canaux de communication divine, apporte une paix profonde et facilite les communications télépathiques et les messages de guidance céleste.",
    guidance: "Vous êtes entouré de guidance divine. Ouvrez-vous aux signes et aux messages — vos anges gardiens vous parlent.",
    howToUse: "Placez sur la gorge ou le troisième œil en méditation pour ouvrir les canaux de communication avec les royaumes angéliques.",
  },
  {
    id: "kyanite-bleue",
    name: "Kyanite Bleue",
    nameEn: "Blue Kyanite",
    color: "bleu électrique",
    colorHex: "#2980B9",
    chakra: "Gorge",
    element: "Air",
    planet: "Jupiter",
    keywords: ["alignement", "communication vérité", "rêves lucides", "équilibre"],
    properties: "Pierre d'alignement et de communication pure, la kyanite bleue aligne tous les chakras sans avoir besoin d'être nettoyée, stimule les rêves lucides et facilite la communication honnête et la résolution des conflits.",
    guidance: "Alignez vos actions à vos valeurs profondes. Quand l'intérieur et l'extérieur sont en harmonie, tout se simplifie.",
    howToUse: "Passez une lame de kyanite le long du corps pour aligner les chakras ou placez sous l'oreiller pour stimuler les rêves conscients.",
  },
  {
    id: "pierre-de-lune",
    name: "Pierre de Lune",
    nameEn: "Moonstone",
    color: "blanc bleuté irisé",
    colorHex: "#D2B4DE",
    chakra: "Couronne",
    element: "Eau",
    planet: "Lune",
    keywords: ["cycles", "intuition féminine", "émotions", "renouveau"],
    properties: "Pierre de la lune et des cycles féminins, la pierre de lune renforce l'intuition, équilibre les émotions et guide dans les transitions de vie. Elle invite à embrasser les cycles naturels et les phases de renouveau.",
    guidance: "Comme la lune, vous traversez des cycles. Honorez chaque phase — même le recul est une préparation au prochain élan.",
    howToUse: "Portez lors des pleines lunes ou placez sur le ventre pour harmoniser les cycles émotionnels et renforcer l'intuition lunaire.",
  },
  {
    id: "heliodore",
    name: "Héliodore",
    nameEn: "Heliodor",
    color: "jaune doré",
    colorHex: "#F8C471",
    chakra: "Plexus Solaire",
    element: "Feu",
    planet: "Soleil",
    keywords: ["lumière solaire", "optimisme", "leadership", "volonté divine"],
    properties: "Pierre de la lumière du soleil et de la volonté divine, l'héliodore stimule la confiance en soi, le leadership naturel et apporte un optimisme rayonnant. Il aligne la volonté personnelle à la volonté supérieure.",
    guidance: "Votre lumière intérieure est un don pour le monde. Rayonnez avec confiance — votre éclat inspire ceux qui vous entourent.",
    howToUse: "Portez sur le plexus solaire ou tenez face au soleil du matin pour absorber l'énergie solaire et renforcer votre confiance.",
  },
  {
    id: "opale",
    name: "Opale",
    nameEn: "Opal",
    color: "multicolore irisé",
    colorHex: "#F0E6FF",
    chakra: "Couronne",
    element: "Eau",
    planet: "Vénus",
    keywords: ["créativité", "spontanéité", "magie des possibles", "transformation"],
    properties: "Pierre de la magie et de l'infini des possibles, l'opale amplifie les émotions, stimule la créativité et ouvre à la spontanéité. Elle reflète les pensées et sentiments les plus profonds comme un miroir de l'âme.",
    guidance: "Toutes les couleurs de votre être ont de la valeur. Embrassez votre complexité — c'est votre richesse la plus précieuse.",
    howToUse: "Portez comme bijou ou méditez en la contemplant pour stimuler la créativité et explorer les multiples facettes de votre être.",
  },
];

export function drawCrystals(count: number): Crystal[] {
  const shuffled = [...CRYSTALS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export interface CrystalSpread {
  id: string;
  name: string;
  count: number;
  positions: string[];
  description: string;
}

export const CRYSTAL_SPREADS: CrystalSpread[] = [
  {
    id: "message-du-jour",
    name: "Message du Jour",
    count: 1,
    positions: ["Guidance du moment présent"],
    description: "Un cristal unique tiré pour recevoir un message vibratoire ciblé pour la journée.",
  },
  {
    id: "corps-ame-esprit",
    name: "Corps · Âme · Esprit",
    count: 3,
    positions: ["Corps — Énergie physique", "Âme — Monde émotionnel", "Esprit — Guidance spirituelle"],
    description: "Trois cristaux pour explorer l'harmonie entre votre corps, votre âme et votre esprit.",
  },
  {
    id: "grille-de-guerison",
    name: "Grille de Guérison",
    count: 5,
    positions: [
      "Centre — Intention principale",
      "Haut — Ce qui élève",
      "Bas — Ce qui ancre",
      "Gauche — Ce qui libère",
      "Droite — Ce qui attire",
    ],
    description: "Cinq cristaux en grille sacrée pour une guérison vibratoire complète sur tous les plans.",
  },
];
